#!/usr/bin/env python3
"""Extract per-file descriptions and build filemap.tsv for agent navigation.

Walks the repository and extracts a one-line description of each file from
language-appropriate conventions, then writes a path-sorted TSV agents read
before exploring rather than searching blind:

    path<TAB>description<TAB>kind

``description`` is the file's own first statement (module docstring paragraph,
heading, manifest title); empty where the file states none, so a known-absent
description stays distinguishable from an unmapped file. ``kind`` is ``src``,
``test``, ``doc`` or ``config``, derived from the path.

Usage:
  uv run --frozen python scripts/generate_filemap.py           # write filemap.tsv
  uv run --frozen python scripts/generate_filemap.py --check   # exit 1 if stale
  uv run --frozen python scripts/generate_filemap.py --stats   # coverage and gaps
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "filemap.tsv"

INCLUDE_EXTENSIONS = frozenset({".py", ".md", ".json", ".toml", ".yaml", ".yml"})

# Data and generated directories are not navigable source; they would flood the
# map with null entries and stale measurements.
EXCLUDE_PATTERNS = [
    re.compile(r"^tests/fixtures/"),
    re.compile(r"^docs/research/"),
    re.compile(r"^sample-data/"),
    re.compile(r"^vendor/"),
    re.compile(r"^filemap\.tsv$"),
]

MAX_DESCRIPTION = 120
HEADER = "# filemap.tsv — auto-generated by scripts/generate_filemap.py; do not hand-edit."


def cap(desc: str) -> str | None:
    desc = " ".join(desc.split())
    if not desc:
        return None
    if len(desc) > MAX_DESCRIPTION:
        cut = desc.rfind(" ", 0, MAX_DESCRIPTION - 1)
        desc = desc[:cut] + "…" if cut > 0 else desc[: MAX_DESCRIPTION - 1] + "…"
    return desc


def _norm(text: str) -> str:
    return re.sub(r"[^a-z0-9]", "", text.lower())


def extract_python(content: str) -> str | None:
    """The module docstring's first paragraph: a summary and its continuation, cut at a word boundary."""
    stripped = re.sub(r"^#!.*\n", "", content)
    stripped = re.sub(r"^(?:#[^\n]*\n|\s*\n)*", "", stripped).lstrip()
    match = re.match(r'^(?:"""|\'\'\')([\s\S]*?)(?:"""|\'\'\')', stripped)
    if not match:
        return None
    paragraph = re.split(r"\n\s*\n", match.group(1), maxsplit=1)[0]
    return cap(paragraph)


def extract_markdown(content: str, rel: str) -> str | None:
    frontmatter = re.match(r"^---\s*\n([\s\S]*?)\n---", content)
    if frontmatter:
        title = re.search(r'^title:\s*["\']?(.+?)["\']?\s*$', frontmatter.group(1), re.MULTILINE)
        if title:
            desc = cap(title.group(1))
            if desc and _norm(desc) != _norm(Path(rel).stem):
                return desc
    heading = re.search(r"^#\s+(.+)", content, re.MULTILINE)
    if heading:
        desc = cap(heading.group(1))
        if desc and _norm(desc) != _norm(Path(rel).stem):
            return desc
    return None


def extract_json(content: str, rel: str) -> str | None:
    try:
        obj = json.loads(content)
    except json.JSONDecodeError:
        return None
    if not isinstance(obj, dict):
        return None
    stem_norm = _norm(Path(rel).stem)
    title = obj.get("title")
    if isinstance(title, str) and _norm(title) != stem_norm:
        return cap(title)
    description = obj.get("description")
    if isinstance(description, str):
        return cap(description)
    schema_id = obj.get("$id")
    if isinstance(schema_id, str) and rel.endswith(".schema.json"):
        return cap(schema_id.rstrip("/").split("/")[-1])
    name = obj.get("name")
    if isinstance(name, str) and _norm(name) != stem_norm:
        return cap(name)
    return None


def extract_toml(content: str) -> str | None:
    match = re.search(r'^\s*description\s*=\s*"([^"]+)"', content, re.MULTILINE)
    return cap(match.group(1)) if match else None


def extract_yaml(content: str, rel: str) -> str | None:
    stem_norm = _norm(Path(rel).stem)
    for key in ("title", "description"):
        match = re.search(rf"^{key}:\s*(.+)$", content, re.MULTILINE)
        if match:
            desc = cap(match.group(1).strip('"').strip("'"))
            if desc and _norm(desc) != stem_norm:
                return desc
    return None


EXTRACTORS = {
    ".py": lambda content, rel: extract_python(content),
    ".md": extract_markdown,
    ".json": extract_json,
    ".toml": lambda content, rel: extract_toml(content),
    ".yaml": extract_yaml,
    ".yml": extract_yaml,
}


def kind_of(rel: str, suffix: str) -> str:
    if suffix == ".md":
        return "doc"
    if suffix == ".py":
        parts = rel.split("/")
        if "tests" in parts or Path(rel).name.startswith(("test_", "conftest")):
            return "test"
        return "src"
    return "config"


def walk_files() -> list[Path]:
    files = []
    for path in sorted(ROOT.rglob("*")):
        if path.suffix not in INCLUDE_EXTENSIONS:
            continue
        if any(part.startswith(".") for part in path.relative_to(ROOT).parts):
            continue
        rel = path.relative_to(ROOT).as_posix()
        if any(pattern.search(rel) for pattern in EXCLUDE_PATTERNS):
            continue
        files.append(path)
    return files


def build_rows() -> list[tuple[str, str, str]]:
    rows = []
    for path in walk_files():
        rel = path.relative_to(ROOT).as_posix()
        try:
            desc = EXTRACTORS[path.suffix](path.read_text(), rel)
        except (OSError, UnicodeDecodeError):
            desc = None
        rows.append((rel, desc or "", kind_of(rel, path.suffix)))
    return sorted(rows)


def render(rows: list[tuple[str, str, str]]) -> str:
    lines = [HEADER, *[f"{rel}\t{desc}\t{kind}" for rel, desc, kind in rows]]
    return "\n".join(lines) + "\n"


def entries_of(text: str) -> list[str]:
    return [line for line in text.splitlines() if line and not line.startswith("#")]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if filemap.tsv is stale")
    parser.add_argument("--stats", action="store_true", help="print coverage and list undescribed files")
    args = parser.parse_args(argv)

    rows = build_rows()
    rendered = render(rows)
    described = sum(1 for _, desc, _ in rows if desc)
    total = len(rows)

    if args.stats:
        print(f"Filemap: {described}/{total} files described ({round(described / total * 100)}%)")
        undescribed = [rel for rel, desc, _ in rows if not desc]
        if 0 < len(undescribed) <= 50:
            print("\nFiles missing descriptions:")
            for rel in undescribed:
                print(f"  {rel}")
        elif undescribed:
            print(f"\n{len(undescribed)} files missing descriptions")
        return 0

    if args.check:
        try:
            existing = entries_of(OUTPUT.read_text())
        except OSError:
            print("filemap.tsv missing. Run: uv run --frozen python scripts/generate_filemap.py", file=sys.stderr)
            return 1
        if existing != entries_of(rendered):
            print("filemap.tsv is stale. Run: uv run --frozen python scripts/generate_filemap.py", file=sys.stderr)
            return 1
        print("filemap.tsv is up to date.")
        return 0

    OUTPUT.write_text(rendered)
    print(f"Wrote {OUTPUT}")
    print(f"Coverage: {described}/{total} files ({round(described / total * 100)}%)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
