"""Rendering: the map's tables, drift diffs and the evidence check each row cites."""

from __future__ import annotations

import re
import subprocess
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from spicy_docs.sources.congress.listing import LIST_ROUTES
from tools.analysis.legislative_data_map._render import _cell, _ordinal
from tools.analysis.legislative_data_map.capture import _identity_order
from tools.analysis.legislative_data_map.comparisons import render_comparisons
from tools.analysis.legislative_data_map.flow import render_flow, render_requirements
from tools.analysis.legislative_data_map.rows import ROWS, A, B, C, D, Row

MARK_START = "<!-- generated by tools/analysis/legislative_data_map.py: start -->"
MARK_END = "<!-- generated by tools/analysis/legislative_data_map.py: end -->"


def diff_measures(previous: Mapping[str, Any], current: Mapping[str, Any]) -> list[str]:
    """What moved between two sidecars: counts, floors, freshness, comparison sets, edge outcomes, sample shapes."""
    lines: list[str] = []
    for route, now in current.get("congress", {}).items():
        was = previous.get("congress", {}).get(route, {})
        for field in ("total", "earliest", "latestUpdate", "latestSortHonored"):
            if was.get(field) != now.get(field):
                lines.append(f"congress {route} {field}: {was.get(field)!r} → {now.get(field)!r}")
    for code, now in current.get("govinfo", {}).get("coverage", {}).items():
        was = previous.get("govinfo", {}).get("coverage", {}).get(code, {})
        for field in ("total", "earliestYear"):
            if was.get(field) != now.get(field):
                lines.append(f"govinfo {code} {field}: {was.get(field)!r} → {now.get(field)!r}")
    for code, now in current.get("govinfo", {}).get("bulkdata", {}).items():
        was = previous.get("govinfo", {}).get("bulkdata", {}).get(code, {})
        if was.get("numericRange") != now.get("numericRange"):
            lines.append(f"bulkdata {code} range: {was.get('numericRange')!r} → {now.get('numericRange')!r}")
    for key, now in current.get("comparisons", {}).items():
        was = previous.get("comparisons", {}).get(key, {})
        for field in ("aCount", "bCount", "both"):
            if was.get(field) != now.get(field):
                lines.append(f"comparison {key} {field}: {was.get(field)!r} → {now.get(field)!r}")
    for key, now in current.get("flow", {}).items():
        was = previous.get("flow", {}).get(key)
        if was is None:
            lines.append(f"edge {key}: new, {'resolved' if now.get('ok') else 'unresolved'}")
        elif was.get("ok") != now.get("ok"):
            lines.append(
                f"edge {key}: {'resolved' if was.get('ok') else 'unresolved'} → {'resolved' if now.get('ok') else 'unresolved'}"
            )
    for key, now in current.get("samples", {}).items():
        was = previous.get("samples", {}).get(key, {})
        root_was, root_now = (was.get("shape") or {}).get("root"), (now.get("shape") or {}).get("root")
        if root_was != root_now or bool(was.get("error")) != bool(now.get("error")):
            lines.append(
                f"sample {key}: root {root_was!r} → {root_now!r}, error {bool(was.get('error'))} → {bool(now.get('error'))}"
            )
    return lines or ["no drift in counts, floors, freshness, comparison sets, edge outcomes or sample shapes"]


# --- rendering -----------------------------------------------------------------


def _congress_cells(facts: Mapping[str, Any]) -> tuple[str, str]:
    if "totalError" in facts and "earliest" not in facts:
        return "error", facts["totalError"].get("message", "")[:60]
    total = facts.get("total")
    count = f"{total:,}" if isinstance(total, int) else ""
    earliest = facts.get("earliest")
    path = facts.get("descentPath", "")
    if earliest is None:
        coverage = "" if not path else f"none found ({facts.get('descentStop')})"
    elif "daily" in path:
        coverage = f"vol. {earliest}+"
    elif "bound" in path:
        coverage = f"{earliest}+"
    else:
        coverage = f"{_ordinal(earliest)} Congress+"
    if facts.get("descentStop") in ("cap", "error") and earliest is not None:
        coverage = f"≥ {coverage[:-1]} ({facts['descentStop']})"
    latest = facts.get("latestUpdate")
    if latest:
        stamp = str(latest)[:10]
        phrase = f"latest {stamp}" if facts.get("latestSortHonored") else f"updated ≥ {stamp} (sort ignored)"
        coverage = f"{coverage}; {phrase}" if coverage else phrase
    return coverage, count


def _govinfo_cells(measures: Mapping[str, Any], code: str) -> tuple[str, str]:
    inventory = measures.get("collections", {}).get(code, {})
    coverage = measures.get("coverage", {}).get(code, {})
    bulk = measures.get("bulkdata", {}).get(code)
    year = coverage.get("earliestYear")
    cov = [f"API {year}+" if year else ("API error" if coverage.get("error") else "")]
    total, count = coverage.get("total"), inventory.get("packageCount")
    if isinstance(total, int) and isinstance(count, int) and total != count:
        # The year search counts packages with an issue date; the inventory counts all. The gap is packages undated.
        cov[0] += f" ({count - total:,} inventory packages undated)"
    if bulk:
        rng = bulk.get("numericRange")
        cov.append(f"bulk {rng[0]}–{rng[1]}" if rng else "bulk, flat")
    parts = []
    if isinstance(inventory.get("packageCount"), int):
        parts.append(f"{inventory['packageCount']:,} pkgs")
    if bulk and bulk.get("topLevelFiles"):
        parts.append(f"bulk {bulk['topLevelFiles']:,} files, {bulk['topLevelBytes'] / 1e6:,.0f} MB")
    current = (bulk or {}).get("currentCongress") or {}
    if current.get("types") and not current.get("zipBytes") and not current.get("fileBytes"):
        parts.append(
            f"{_ordinal(current['congress'])} bulk nested one level deeper ({', '.join(current['types'])}); unsized"
        )
    elif current.get("zipBytes") or current.get("fileBytes"):
        modified = next((t.get("zipModified") for t in current.get("types", {}).values() if t.get("zipModified")), None)
        parts.append(
            f"{_ordinal(current['congress'])} zips {current['zipBytes'] / 1e6:,.0f} MB, {current['files']:,} files"
            + (f", zip modified {modified}" if modified else "")
        )
    return "; ".join(c for c in cov if c), "; ".join(parts)


def _sample_cells(facts: Mapping[str, Any]) -> tuple[str, str]:
    if "error" in facts:
        reason = facts.get("message", facts["error"]).split(";")[0][:70]
        return "", f"sample refused: HTTP {facts['statusCode']}" if facts.get(
            "statusCode"
        ) else f"sample refused: {reason}"
    shape = facts.get("shape", {})
    root = shape.get("root")
    if root:
        identity = _identity_order(shape.get("identityNames") or [])
        dated = shape.get("datedNames") or []
        if identity:
            stated = f"names {', '.join(identity[:4])}"
        elif dated:
            stated = f"dated only ({', '.join(dated[:2])})"
        else:
            stated = "no identity element within two levels"
        detail = f"root `{root}`, {shape.get('childCount', 0)} children; {stated}"
    elif shape.get("idKinds"):
        kinds = shape["idKinds"]
        named = ", ".join(
            f"{k} {v:,}"
            for k, v in kinds.items()
            if k in ("bioguide", "lis", "fec", "icpsr", "govtrack", "opensecrets")
        )
        detail = f"{shape.get('count', 0):,} records; ids {named}"
    elif isinstance(shape.get("count"), int):
        detail = f"declares {shape['count']:,} records"
    elif shape.get("html"):
        detail = "HTML page"
    else:
        detail = f"keys {', '.join(shape.get('keys', [])[:4])}"
    return "", f"sample {facts.get('byteSize', 0):,} B, {detail}"


def _cells(row: Row, measures: Mapping[str, Any]) -> tuple[str, str]:
    if row.measure is None:
        return "", ""
    kind, key = row.measure
    if kind == "congress":
        return _congress_cells(measures.get("congress", {}).get(key, {}))
    if kind == "govinfo":
        return _govinfo_cells(measures.get("govinfo", {}), key)
    if kind == "sample":
        return _sample_cells(measures.get("samples", {}).get(key, {}))
    if kind == "cdtf":
        entry = measures.get("catalog", {}).get("byId", {}).get(key, {})
        return "", f"CDTF #{key}, {entry.get('accrualPeriodicity', '')}"
    raise ValueError(f"unknown measure kind {kind!r}")


TABLES = {
    A: "Table A: Congress.gov API. One credential family, one pagination contract, one reader; a route is a URL builder and a records key.",
    B: "Table B: GovInfo API and bulkdata. Discovery and MODS already reach any collection; what differs per collection is the body fetch.",
    C: "Table C: publisher XML, feeds and sites. Keyless; the sample column shows what the payload states about itself.",
    D: "Table D: civil society, BillTrax-side and interpretation.",
}


def render_tables(measures: Mapping[str, Any]) -> str:
    lines = [MARK_START, ""]
    generated = measures.get("generatedAt", "")
    lines.append(
        f"Measured {generated[:10]} by `tools/analysis/legislative_data_map.py` at spicy-docs `{measures.get('revision', '')}`; "
        f"{measures.get('requests', {}).get('total', '?')} requests. Coverage is the earliest populated Congress, volume or "
        f"year the publisher answered for, a lower bound; `(cap)` means the walk ended at its request cap and `(error)` "
        f"that it stopped on repeated publisher errors, both detailed in the JSON. Latest is the newest update date "
        f"the publisher reports for the route."
    )
    lines.append("")
    for table, caption in TABLES.items():
        lines += [
            f"### {caption}",
            "",
            "| Subject | Data | Route | Status | Credential | Coverage | Count / sample | Note |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for row in ROWS:
            if row.table != table:
                continue
            coverage, count = _cells(row, measures)
            lines.append(
                "| "
                + " | ".join(
                    _cell(v)
                    for v in (
                        row.subject,
                        row.data,
                        row.route,
                        f"`{row.status}`",
                        row.credential,
                        coverage,
                        count,
                        row.note,
                    )
                )
                + " |"
            )
        lines.append("")
    lines += render_comparisons(measures)
    lines += render_flow(measures)
    lines += render_requirements(measures)
    catalog = measures.get("catalog", {})
    dist = catalog.get("distributionAccessUrl", {})
    duplicates = ", ".join(f"`{u}` ×{n}" for u, n in catalog.get("duplicateLandingPages", {}).items()) or "none"
    lines.append("### Catalog measurements")
    lines.append("")
    lines.append(
        f"- CDTF entries: {catalog.get('entries')}; with `accrualPeriodicity`: {catalog.get('withAccrualPeriodicity')}; "
        f"with any format or temporal field: {catalog.get('withFormatOrTemporal')}."
    )
    lines.append(
        f"- `distribution.accessURL`: {dist.get('homepageRoot')} bare homepage roots, {dist.get('deep')} deep links, "
        f"{dist.get('missing')} missing. The real URL is `landingPage.accessURL`, nested in an object."
    )
    lines.append(f"- Duplicate landing pages: {duplicates}.")
    lines.append("")
    lines.append(MARK_END)
    return "\n".join(lines)


def rewrite_map(path: Path, tables: str) -> None:
    text = path.read_text()
    start, end = text.find(MARK_START), text.find(MARK_END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit(f"{path} lacks the generated-table markers")
    path.write_text(text[:start] + tables + text[end + len(MARK_END) :])


# --- main ----------------------------------------------------------------------


PROOFS: dict[str, str] = {
    "Bill metadata, status, text versions": "BILLSTATUS",
    "CRS bill summaries": "summaries",
    "Amendments listing": "amendment",
    "Committee-referred bills": "committee-bills",
    "Vote references on bill actions (`recordedVotes`)": "bill-actions",
    "Nominations": "nomination",
    "Hearings": "hearing",
    "Committee reports": "committee-report",
    "House executive communications": "house-communication",
    "Community legislators JSON (current + historical)": "lis",
    "Committee report bodies": "CRPT",
    "Hearing transcript bodies": "CHRG",
    "Congressional documents": "CDOC",
    "Congressional Record bodies": "CREC",
    "Congressional Directory": "CDIR",
    "CRS report metadata and summaries": "crsreport",
    "BILLSTATUS bulk ZIP": "BILLSTATUS",
    "Bill PDFs": "govinfo-pdf-fetch",
    "Public and private laws (PLAW)": "public and private laws",
    "Statute compilations (COMPS)": "statute compilations",
    "MODS, PREMIS, discovery": "MODS",
    "Senate LDA filings": "Lobbying Disclosure",
    "GAO reports and testimony feed, files": "GAO",
    "GAO product pages": "Zyte",
    "CBO cost-estimate feeds": "cost-estimate",
    "US Code, Popular Names, Table III": "Table III",
    "CRS report PDFs": "CRS report",
    "Press releases (member and committee RSS)": "press-releases",
    "Agency uploaded-report PDFs": "report-parser",
}


LISTING_MODULE = "src/spicy_docs/sources/congress/listing.py"
_NOTE_CALL = re.compile(r"`([A-Za-z_][A-Za-z0-9_]*)\(")
_NOTE_BARE = re.compile(r"`([A-Za-z_][A-Za-z0-9_]*)`")


def _note_symbols(note: str) -> list[str]:
    """Backtick names in `note` shaped like a Python function or class, not a field, file or acronym.

    A call form (`` `name(` ``) or a bare backtick identifier is a candidate only if it also reads as a
    Python name: PascalCase and not ALL_CAPS (a class, not an acronym like `RIN`), or snake_case with an
    underscore (a function, not a bare lowercase word like `bioguide` or `hearing`).
    """
    candidates = {*_NOTE_CALL.findall(note), *_NOTE_BARE.findall(note)}
    return [
        name for name in candidates if (name[:1].isupper() and not name.isupper()) or ("_" in name and name.islower())
    ]


def _defines(texts: list[str], name: str) -> bool:
    return any(re.search(rf"\b(?:def|class)\s+{re.escape(name)}\b", text) for text in texts)


def check_evidence(root: Path) -> None:
    """Every `have` or `port` row names a repo path that exists and whose text states what the row claims.

    Two narrower claims get their own check, because a route's or a symbol's *name* is a specific,
    checkable fact, and a row has previously been wrong about both while still citing a real file: a row
    citing `congress/listing.py` for a route (its `measure` key) must name a live `LIST_ROUTES` key, not
    a plausible-looking string, and a function or class the note names (backtick, PascalCase or
    snake_case) must actually be defined in one of the row's evidence files.
    """
    missing = [(row.data, p) for row in ROWS for p in row.evidence if not (root / p).exists()]
    claims = [row.data for row in ROWS if row.status.startswith(("have", "port")) and not row.evidence]
    unproven = []
    unrouted = []
    unsymboled = []
    for row in ROWS:
        texts = [(root / p).read_text(errors="replace") for p in row.evidence if (root / p).is_file()]
        if row.status.startswith(("have", "port")):
            if row.measure is not None and LISTING_MODULE in row.evidence and row.measure[1] not in LIST_ROUTES:
                unrouted.append((row.data, row.measure[1]))
            for name in _note_symbols(row.note):
                if not _defines(texts, name):
                    unsymboled.append((row.data, name))
        phrase = PROOFS.get(row.data)
        if not phrase or not row.evidence:
            continue
        if not any(phrase.lower() in text.lower() for text in texts):
            unproven.append((row.data, phrase))
    if missing or claims or unproven or unrouted or unsymboled:
        for data, p in missing:
            print(f"evidence missing for {data!r}: {p}", file=sys.stderr)
        for data in claims:
            print(f"no evidence named for {data!r}", file=sys.stderr)
        for data, phrase in unproven:
            print(f"evidence for {data!r} never states {phrase!r}", file=sys.stderr)
        for data, key in unrouted:
            print(f"{data!r} cites listing.py for route {key!r}, not a LIST_ROUTES key", file=sys.stderr)
        for data, name in unsymboled:
            print(f"{data!r} names {name!r}, not defined in its evidence", file=sys.stderr)
        raise SystemExit(2)


def _revision(root: Path) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], cwd=root, capture_output=True, text=True, check=False
    )
    return result.stdout.strip() or "unknown"
