"""Measure how far a bill's HTML rendition is from its XML, to size the ``bill_dtd`` profile.

Pre-113th bills offer HTML and PDF only, so the proposal in
``docs/research/closing-the-gaps-2026-09-19.md`` (gap B1, section 3.1) would reconstruct the bill DTD
from the HTML; this tool asks the paired question on Congresses that have both -- hide the XML, read
the HTML, count what deterministic rules recover. Run from the repository root:

  uv run --frozen python -m tools.analysis.bill_html_xml_gap \\
      --env-file .env --cache <scratchpad>/bill-gap \\
      --output docs/research/bill-html-xml-gap-2026-09-19.json \\
      --doc docs/research/bill-html-xml-gap-2026-09-19.md

Add ``--selection held-out`` for the same listings at disjoint quantiles, and ``--offline`` to rewrite
the document's generated block without the network. Bytes land in ``--cache`` and are reused on a
rerun, so a second run with a full cache makes no request.

The rules were revised against the ``tuning`` draw, so scoring those documents again measures the fit;
``--selection held-out`` excludes every tuning package (a quantile landing on an excluded file steps
forward, and the run refuses if any overlap survives) and the held-out score is what the document leads
with, the in-sample one labelled an upper bound. Four measurements, each with what it cannot see: text
fidelity (both renditions through ``extraction.body_text``, then casefold, dash and word-token
normalization, with difflib ratios and one-sided words whole-document and body-only -- casefold loses
that the HTML sets headings in capitals, which the profile must restore from XML conventions);
structure by rule (both section spellings, run-in forms, subsections, title/division banners with
content lists excluded on a nearby column-0 ``Sec. n.``, quoted blocks, and the ``<DELETED>`` struck
markers; scored per kind against ``parse_bill_tree``, matching the enumerator as a multiset, with
unnumbered body sections held out of the section denominator); inventory (kept vs
``discarded_elements`` against HTML tags and HTML-only text features); and pre-113th drift (ten bodies,
one per Congress from the 103rd, no XML to score against). Each draw is thirty pairs from five bulk
listings -- too few to see a rare shape, and the struck rule rests on one in-sample document and the
committed fixtures because the held-out draw contains no two-body document. The DTD is pinned by URL,
byte count and digest and **cited, not validated against**; a credential refusal (401/403) aborts the
run, and the sidecar carries no credential.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import re
import statistics
import subprocess
import sys
from collections import Counter
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import asdict, dataclass, field, replace
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from spicy_docs.extraction.body_text import rendition_text
from spicy_docs.reading.markup import read_html_events
from spicy_docs.reading.paged_json import PagedJsonBudget
from spicy_docs.reading.xml import parse_xml
from spicy_docs.sources.congress.bill_tree import BillDocument, parse_bill_tree
from spicy_docs.sources.congress.listing import CongressListingReader
from spicy_docs.sources.govinfo.bodies import PACKAGE_BODY_FORMATS, package_body_locator, parse_package_id
from spicy_docs.sources.govinfo.error_page import check_not_error_page
from spicy_docs.transport.credentials import CredentialRefusedError, read_api_key, scrub_credential
from tools.analysis.shared import CONGRESS_API, GOVINFO_BULK, JSON_TYPES, KeylessProbe, ProbeError, local_name

MARK_START = "<!-- generated by tools/analysis/bill_html_xml_gap.py: start -->"
MARK_END = "<!-- generated by tools/analysis/bill_html_xml_gap.py: end -->"
MAX_REQUESTS = 90
#: ``KeylessProbe`` allows itself two attempts per operation.
PROBE_ATTEMPTS = 2
BODY_MAX_BYTES = 24 * 1024 * 1024
LISTING_MAX_BYTES = 16 * 1024 * 1024
DTD_URL = "https://xml.house.gov/bill.dtd"
DTD_MEDIA_TYPES = ("application/xml-dtd", "text/plain", "text/xml", "application/octet-stream")
#: Where the run's command, its full output and the per-document digests are
#: retained, outside this repository, per AGENTS.md. The JSON sidecar is the
#: committed pin; the receipt is the evidence that produced it.
RECEIPTS = "~/Work/corpora/supply-2026-09-02/receipts/bill-html-xml-gap-2026-09-19/"
REQUESTS: Counter[str] = Counter()


# --- the corpus, as data ----------------------------------------------------------


@dataclass(frozen=True)
class Selection:
    """How the paired corpus is drawn: which listings, and which files of each."""

    listings: tuple[tuple[int, int, str], ...]
    quantiles: tuple[float, ...]
    picks_per_listing: int


#: The tuning corpus: the documents the rules were revised against. Its score
#: is an in-sample upper bound and the document says so.
SELECTION = Selection(
    listings=((113, 1, "hr"), (113, 2, "s"), (113, 1, "hjres"), (114, 2, "hr"), (114, 1, "sres")),
    quantiles=(0.5, 0.95),
    picks_per_listing=6,
)

#: The held-out corpus: the same listings at **disjoint** quantiles, so no
#: document the rules were revised against can appear in it. Drawn and scored
#: once, after the rules were frozen; that score, not ``SELECTION``'s, is what
#: the document leads with. The listings are deliberately the same, so the two
#: differ only in which files they take and the comparison is about tuning
#: rather than about a different slice of the corpus.
HELD_OUT = Selection(
    listings=SELECTION.listings,
    quantiles=(0.25, 0.75),
    picks_per_listing=6,
)

SELECTIONS: dict[str, Selection] = {"tuning": SELECTION, "held-out": HELD_OUT}

#: Pre-113th bodies. Two package ids were proved on 2026-09-19 by
#: ``GovInfoBodyAcquirer`` in the PDF-only census (``offered=('htm','pdf')``);
#: the rest are H.R. 1 of each other Congress, whose newest text version is
#: read from the keyed Congress.gov text route so the package id is the
#: publisher's own statement rather than a guess. H.R. 1 because every
#: Congress introduces one and most reach a later printing.
PRE_113_PROVEN = ("BILLS-103hr1enr", "BILLS-109s256enr")
PRE_113_LOOKUPS = tuple((congress, "hr", 1) for congress in (104, 105, 106, 107, 108, 110, 111, 112))


# --- fetching, cached -----------------------------------------------------------------


class RequestBudgetExhausted(RuntimeError):
    """The run reached ``MAX_REQUESTS``; what is cached is measured, the rest is refused."""


def _guarded[Result](client: Any, kind: str, attempts: int, call: Callable[[], Result]) -> Result:
    """One operation against the run's budget, counting every attempt it makes, refusal or not.

    The client retries a transport failure up to its own ``max_requests``, so
    the guard reserves that many before the call and reads the count the
    client reports afterwards, which is the attempts actually made.
    """
    if sum(REQUESTS.values()) + attempts > MAX_REQUESTS:
        raise RequestBudgetExhausted(f"{MAX_REQUESTS}-request budget would be exceeded")
    try:
        return call()
    finally:
        REQUESTS[kind] += client.request_count


def _cached(path: Path, fetch: Callable[[], bytes]) -> bytes:
    """The file's bytes, fetching and writing them first when it does not exist yet."""
    if not path.exists():
        body = fetch()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(body)
    return path.read_bytes()


def fetch_listing(probe: KeylessProbe, cache: Path, congress: int, session: int, bill_type: str) -> list[dict]:
    """One bulk listing's ``files`` array, cached by its own path and counted against the run budget."""
    body = _cached(
        cache / "listings" / f"BILLS-{congress}-{session}-{bill_type}.json",
        lambda: _guarded(
            probe,
            "keyless",
            PROBE_ATTEMPTS,
            lambda: (
                probe.get(
                    f"{GOVINFO_BULK}/BILLS/{congress}/{session}/{bill_type}",
                    media_types=JSON_TYPES,
                    max_bytes=LISTING_MAX_BYTES,
                    accept="application/json",
                ).body
            ),
        ),
    )
    return json.loads(body).get("files", [])


def fetch_body(probe: KeylessProbe, cache: Path, package_id: str, rendition: str) -> bytes:
    """One keyless rendition, refused if the publisher answered with its error page."""
    body_format = PACKAGE_BODY_FORMATS[rendition]

    def fetch() -> bytes:
        capture = _guarded(
            probe,
            "keyless",
            PROBE_ATTEMPTS,
            lambda: probe.get(
                package_body_locator(package_id, rendition),
                media_types=body_format.media_types,
                max_bytes=BODY_MAX_BYTES,
            ),
        )
        check_not_error_page(
            capture.body,
            capture.resolved_url,
            error_type=ProbeError,
            message=f"{package_id} {rendition}: govinfo answered its error page",
        )
        return capture.body

    return _cached(cache / "bodies" / f"{package_id}.{body_format.extension}", fetch)


def fetch_text_versions(
    reader: CongressListingReader, cache: Path, congress: int, bill_type: str, number: int
) -> list[Mapping[str, Any]]:
    """The keyed text route's ``textVersions``; the credential travels as a header and is never cached."""

    def fetch() -> bytes:
        page = _guarded(
            reader,
            "keyed",
            reader.budget.max_requests,
            lambda: reader.page(
                f"{CONGRESS_API}/bill/{congress}/{bill_type}/{number}/text?format=json", records_key="textVersions"
            ),
        )
        return json.dumps([dict(row) for row in page.records], indent=1, sort_keys=True, default=str).encode()

    return json.loads(_cached(cache / "text-routes" / f"{congress}-{bill_type}-{number}.json", fetch))


@dataclass(frozen=True)
class DtdPin:
    """The fetched DTD with the pin that identifies it.

    The bytes and their digest are recorded, not just the models derived from
    them, so a later reader can tell whether the schema this measurement read
    is the schema they hold. Nothing here validates a document *against* the
    DTD; that is the profile's work, and the document says so.
    """

    url: str
    byte_size: int
    sha256: str
    text: str

    def pin(self) -> dict[str, Any]:
        """The DTD's URL, byte count and digest, as the sidecar records them."""
        return {"dtdUrl": self.url, "dtdBytes": self.byte_size, "dtdSha256": self.sha256}


def fetch_dtd(probe: KeylessProbe, cache: Path) -> DtdPin | None:
    """The target DTD, so the required elements are read from the schema rather than remembered."""
    try:
        body = _cached(
            cache / "bill.dtd",
            lambda: _guarded(
                probe,
                "keyless",
                PROBE_ATTEMPTS,
                lambda: probe.get(DTD_URL, media_types=DTD_MEDIA_TYPES, max_bytes=1 << 20).body,
            ),
        )
    except (ProbeError, RequestBudgetExhausted):
        return None
    return DtdPin(DTD_URL, len(body), hashlib.sha256(body).hexdigest(), body.decode(errors="replace"))


#: Whether the DTD declares an element by this name. ``<DELETED>`` does not
#: appear: the schema declares ``deleted-phrase`` (a phrase-level element whose
#: ``reported-display-style`` includes ``strikethrough``) and a ``changed``
#: attribute taking ``deleted``, neither of which is the print marker. So the
#: marker is a GPO **print convention inferred from this corpus**, not a
#: documented element, and the XML expresses the same fact structurally, as a
#: second ``<legis-body>``. ``dtd_declares`` records that rather than asserting
#: it from memory.
def dtd_declares(dtd: DtdPin | None, name: str) -> bool | None:
    """Whether the DTD has an ``<!ELEMENT name ...`` declaration, or None when no DTD was fetched."""
    if dtd is None:
        return None
    return re.search(rf"<!ELEMENT\s+{re.escape(name)}\s", dtd.text) is not None


def stated_package_id(versions: Sequence[Mapping[str, Any]]) -> str | None:
    """The newest version whose stated format URL carries a BILLS package id in its stem."""
    for version in versions:
        for item in version.get("formats") or ():
            url = item.get("url")
            if not isinstance(url, str):
                continue
            stem = Path(urlsplit(url).path).stem
            try:
                parse_package_id(stem)
            except ValueError:
                continue
            return stem
    return None


# --- corpus selection ------------------------------------------------------------------


def _version_code(package_id: str) -> str:
    """The version code a BILLS package id states, or the empty string when it states none."""
    return parse_package_id(package_id).version or ""


def select_pairs(
    entries: Iterable[Mapping[str, Any]],
    selection: Selection = SELECTION,
    exclude: frozenset[str] = frozenset(),
) -> list[str]:
    """Package ids from one listing: codes by descending file count, each at the selection's quantiles.

    ``exclude`` makes a held-out draw provably disjoint from the corpus the
    rules were tuned on rather than merely likely to be: a quantile index that
    lands on an excluded file steps forward through that code's files, in size
    order, until it finds one that is not excluded. Without it, a version code
    with few files resolves every quantile to the same document and the
    "held-out" sample would quietly re-score the tuning set.
    """
    by_code: dict[str, list[tuple[int, str]]] = {}
    for entry in entries:
        if entry.get("fileExtension") != "xml":
            continue
        package_id = str(entry.get("justFileName", "")).removesuffix(".xml")
        try:
            code = _version_code(package_id)
        except ValueError:
            continue
        by_code.setdefault(code, []).append((int(entry.get("size") or 0), package_id))
    codes = sorted(by_code, key=lambda code: (-len(by_code[code]), code))
    picks: list[str] = []
    for quantile in selection.quantiles:
        for code in codes:
            if len(picks) >= selection.picks_per_listing:
                return picks
            files = sorted(by_code[code])
            start = min(len(files) - 1, int(quantile * (len(files) - 1)))
            for step in range(len(files)):
                _, package_id = files[(start + step) % len(files)]
                if package_id not in exclude and package_id not in picks:
                    picks.append(package_id)
                    break
    return picks


# --- text fidelity ---------------------------------------------------------------------

_DASHES = re.compile(r"--|[—–]")
_WORD = re.compile(r"[^\W_]+")


def normalized_words(text: str) -> list[str]:
    """The one normalization both sides get: casefold, dashes as separators, word tokens."""
    return _WORD.findall(_DASHES.sub(" ", text.casefold()))


def fidelity(html_words: Sequence[str], xml_words: Sequence[str], *, top: int = 12) -> dict[str, Any]:
    """difflib's ratio over the two word sequences, plus the most common words only one side holds."""
    ratio = (
        difflib.SequenceMatcher(None, html_words, xml_words, autojunk=False).ratio()
        if html_words and xml_words
        else 0.0
    )
    html_only = Counter(html_words) - Counter(xml_words)
    xml_only = Counter(xml_words) - Counter(html_words)
    return {
        "ratio": round(ratio, 4),
        "htmlWords": len(html_words),
        "xmlWords": len(xml_words),
        "htmlOnly": {"count": sum(html_only.values()), "top": html_only.most_common(top)},
        "xmlOnly": {"count": sum(xml_only.values()), "top": xml_only.most_common(top)},
    }


# --- structure rules over the HTML rendition's text -------------------------------------

#: GPO's marker for a reported bill's struck committee-substitute text. It is
#: not markup here: GPO escapes it in the ``htm`` rendition, so the markup
#: reader hands it back as text. It wraps a whole provision and sits *outside*
#: that provision's own indentation (``<DELETED>    (a) Amendment.--``), so it
#: is stripped from every line once, before any rule runs, rather than being
#: spelled as an optional prefix and suffix in four separate patterns.
#: Recovering it is what recovers the second ``<legis-body>`` the engine
#: reports for a reported bill.
STRUCK_MARKER = re.compile(r"</?DELETED>")
#: A displayed section heading: ``SEC. 3.`` or ``SECTION 1.`` in capitals at
#: the line start.
SECTION_UPPER = re.compile(r"^(?:SECTION|SEC\.)\s+(\d+[A-Z]?)\.\s*(.*)$")
#: An appropriations general provision, which GPO sets as a run-in at the same
#: four-space indent as body prose: ``    Sec. 1201.  Any appropriations…``.
#: Measured on the paired corpus: every document is either all-uppercase or
#: all-run-in, never both, and the run-in form carries no separate catchline.
SECTION_RUNIN = re.compile(r"^ {4}Sec\.\s+(\d+[A-Z]?)\.\s+(.*)$")
#: A subsection at the ``<pre>`` rendition's four-space indent.
SUBSECTION = re.compile(r"^ {4}\(([a-z]+)\)\s")
#: A subsection opening on the same line as a run-in section heading.
INLINE_SUBSECTION = re.compile(r"^\(([a-z]+)\)\s")
TITLE = re.compile(r"^\s*TITLE\s+([IVXLCDM]+)\b")
DIVISION = re.compile(r"^\s*DIVISION\s+([A-Z]+)\b")
#: A table-of-contents entry, which GPO sets at column 0 with its continuation
#: indented -- the one place ``Sec. n.`` appears outside a provision.
TOC_ENTRY = re.compile(r"^Sec\.\s+\d+[A-Z]?\.\s")
QUOTE_START = re.compile(r'^\s*"')
QUOTE_END = re.compile(r'"[.;,]?(?: (?:and|or))?$')
#: GPO introduces block amendment payload with a colon (``…by inserting the
#: following:``) and a blank line. The lead-in is what separates a block from
#: an inline quoted term, which the XML spells ``<quote>``, not
#: ``<quoted-block>`` -- and only a block may run past its own line. Measured:
#: a line merely *opening* with a quote is ordinary prose naming two quoted
#: account titles, and letting it open a span swallowed five section headings
#: of BILLS-113hjres91enr before a later line happened to close it.
QUOTE_LEAD_IN = re.compile(r":$")
#: Where a document's body begins when it states no numbered section: the
#: enacting or resolving clause. A simple resolution has no section heading at
#: all, and anchoring its body at the top of the file would compare its whole
#: printed preamble against a ``resolution-body`` that starts after the clause.
RESOLVING_CLAUSE = re.compile(r"^\s*(?:Be it enacted|Resolved)\b")
BANNER = re.compile(r"^\[.*\]$")
RULE_LINE = re.compile(r"^_{10,}$")
PAGE_MARKER = re.compile(r"\[\[Page \d+\]\]")
HEADER_CONTINUATION = re.compile(r"^ {6,}\S")
#: DeltaTrack's ``_valid_subsection_enum`` rejects these as roman lookalikes
#: when it has only the enumerator to go on; the indent rule does not need to.
ROMAN_LOOKALIKES = re.compile(r"^(?:[ivx]|[a-z]{2})$")
TOC_WINDOW = 3


@dataclass
class HtmlStructure:
    """What the rules found in one HTML body."""

    sections: list[tuple[str, str]] = field(default_factory=list)
    subsections: list[tuple[str, str]] = field(default_factory=list)
    titles: list[str] = field(default_factory=list)
    divisions: list[str] = field(default_factory=list)
    quoted_blocks: int = 0
    toc_banners: int = 0
    toc_entries: int = 0
    roman_subsections: int = 0
    inline_enum_headings: int = 0
    runin_sections: int = 0
    struck_sections: int = 0
    quote_terms: int = 0
    banners: list[str] = field(default_factory=list)
    markers: dict[str, int] = field(default_factory=dict)
    first_heading_line: int | None = None
    resolving_clause_line: int | None = None

    @property
    def body_start(self) -> int:
        """The line the printed body begins on: its first section heading, else its resolving clause."""
        for candidate in (self.first_heading_line, self.resolving_clause_line):
            if candidate is not None:
                return candidate
        return 0

    def counts(self) -> dict[str, int]:
        """This structure's per-kind counts, in the keys the XML side uses."""
        return {
            "section": len(self.sections),
            "subsection": len(self.subsections),
            "title": len(self.titles),
            "division": len(self.divisions),
            "quotedBlock": self.quoted_blocks,
        }


def _is_toc_banner(lines: Sequence[str], index: int) -> bool:
    """Whether this TITLE or DIVISION banner is a contents-list entry rather than the real thing.

    The witness is a column-0 ``Sec. n.`` entry close below it. Other banners
    in between do not end the search and do not spend the window: a contents
    list sets every level it covers, so a DIVISION banner is routinely followed
    by its TITLE banners before the first section entry, and counting those
    against the window is what let a contents list's own divisions through as
    real ones.
    """
    seen = 0
    # Indexed, not sliced: ``lines[index + 1:]`` copies the tail of the
    # document at every banner, making the scan O(S*L) for S headings and L
    # lines. Measured both ways over a doubling series and over all 70
    # measured documents (receipt: ``scan_html_scaling.py`` and its output,
    # beside this measurement's other receipts): identical output, and over a
    # 64x growth in line count the sliced form's per-line cost rose 12.1x
    # while the indexed form's stayed flat at 1.0x. At real document sizes the
    # difference is small -- the largest body measured is 37,319 lines, where
    # sliced costs 0.62 us/line against indexed 0.52 -- so this is about the
    # curve, not about today's corpus being slow.
    for probe in range(index + 1, len(lines)):
        line = lines[probe]
        if not line.strip() or TITLE.match(line) or DIVISION.match(line):
            continue
        if TOC_ENTRY.match(line):
            return True
        seen += 1
        if seen >= TOC_WINDOW:
            break
    return False


def _section_header(lines: Sequence[str], index: int, first: str) -> str:
    parts = [first]
    # Indexed for the same reason as _is_toc_banner above.
    for probe in range(index + 1, len(lines)):
        line = lines[probe]
        stripped = line.strip()
        if not stripped or not HEADER_CONTINUATION.match(line) or any(c.islower() for c in stripped):
            break
        parts.append(stripped)
    return " ".join(parts).rstrip(".").strip()


def _is_section_line(line: str) -> bool:
    """Whether a line is a section heading in either spelling; the quote span's stop rule."""
    return bool(SECTION_UPPER.match(line) or SECTION_RUNIN.match(line))


def scan_html(text: str) -> HtmlStructure:
    """One pass over the lines; ``O(L)`` for ``L`` lines plus the bounded TOC look-ahead.

    Order is load-bearing. A quoted line is settled first, because amendment
    payload spells every structure this document does and belongs to the law
    being amended, not to this bill -- the same self-exclusion DeltaTrack's own
    anchor matcher makes. A table-of-contents entry is settled next, so a
    contents list never contributes a section.

    ``<DELETED>`` markers come off every line before any rule runs, so a struck
    provision is read exactly like a live one and is only *counted* apart.
    """
    raw = text.split("\n")
    struck_lines = [STRUCK_MARKER.search(line) is not None for line in raw]
    lines = [STRUCK_MARKER.sub("", line) for line in raw]
    found = HtmlStructure()
    section = ""
    in_quote = False
    at_top = True
    previous = ""
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped:
            continue
        # The banners are the bracketed lines before anything else; a
        # bracketed line further down is content.
        if at_top and BANNER.match(stripped):
            found.banners.append(stripped)
            continue
        at_top = False
        if RULE_LINE.match(stripped):
            found.markers["ruleLine"] = found.markers.get("ruleLine", 0) + 1
        if stripped == "<all>":
            found.markers["<all>"] = found.markers.get("<all>", 0) + 1
        found.markers["[[Page]]"] = found.markers.get("[[Page]]", 0) + len(PAGE_MARKER.findall(line))
        if found.resolving_clause_line is None and RESOLVING_CLAUSE.match(line):
            found.resolving_clause_line = index
        if in_quote:
            # A block ends at its closing quote, or at the next unquoted
            # section heading -- amendment payload never continues through one,
            # and without that stop a block whose close is missed runs to the
            # end of the document. The heading itself is then read normally.
            if not _is_section_line(line):
                in_quote = not QUOTE_END.search(stripped)
                previous = stripped
                continue
            in_quote = False
        elif QUOTE_START.match(line):
            # Only a block opened by GPO's ``:`` lead-in spans lines; a line
            # merely opening with a quote is prose carrying a quoted term.
            if QUOTE_LEAD_IN.search(previous):
                found.quoted_blocks += 1
                in_quote = not QUOTE_END.search(stripped)
            else:
                found.quote_terms += 1
            previous = stripped
            continue
        if TOC_ENTRY.match(line):
            found.toc_entries += 1
        elif (match := SECTION_UPPER.match(line)) or (runin := SECTION_RUNIN.match(line)):
            number, rest = (match[1], match[2]) if match else (runin[1], runin[2])
            section = number
            if found.first_heading_line is None:
                found.first_heading_line = index
            found.struck_sections += struck_lines[index]
            found.runin_sections += match is None
            # The uppercase form sets its catchline on the heading line and
            # may wrap; the run-in form has none, its text starts immediately.
            header = _section_header(lines, index, rest) if match else ""
            if inline := INLINE_SUBSECTION.match(rest):
                found.inline_enum_headings += 1
                found.subsections.append((number, inline[1]))
            found.sections.append((section, header))
        elif match := SUBSECTION.match(line):
            found.subsections.append((section, match[1]))
            if ROMAN_LOOKALIKES.match(match[1]):
                found.roman_subsections += 1
        elif match := DIVISION.match(line):
            if _is_toc_banner(lines, index):
                found.toc_banners += 1
            else:
                found.divisions.append(match[1])
        elif match := TITLE.match(line):
            if _is_toc_banner(lines, index):
                found.toc_banners += 1
            else:
                found.titles.append(match[1])
        previous = stripped
    found.markers = {name: count for name, count in found.markers.items() if count}
    return found


def sequence_check(numbers: Sequence[str]) -> dict[str, int]:
    """How often a detected section number fails to advance; restarts under a new division are expected."""
    previous = 0
    non_increasing = 0
    for number in numbers:
        value = int(re.match(r"\d+", number)[0])
        if value <= previous:
            non_increasing += 1
        previous = value
    return {"nonIncreasing": non_increasing, "duplicates": sum(count - 1 for count in Counter(numbers).values())}


# --- the XML reference ------------------------------------------------------------------

_XML_BODIES = ("legis-body", "resolution-body", "engrossed-amendment-body")
_SECTION_NUMBER = re.compile(r"^Sec\.\s*(\S+)")
_ENUM = re.compile(r"^\(([a-z]+)\)")
_TITLE_LABEL = re.compile(r"^TITLE\s+(\S+?)(?:[—–—]|$)")
_DIVISION_LABEL = re.compile(r"^Division\s+(\S+?):?(?:\s|$)")


@dataclass(frozen=True)
class XmlStructure:
    """The engine's nodes in the keys the HTML rules produce.

    ``unnumbered_sections`` are body ``<section>`` elements the engine emits
    with no ``<enum>``: a resolution's resolving-clause body and a trailing
    short-title section. They print with **no heading of any kind**, so they
    are held apart from ``sections`` rather than counted as headings the rules
    missed -- a heading rule cannot find what was never set as a heading. What
    that separation cannot see is whether a boundary rule would place them
    correctly; nothing here tests one.
    """

    sections: list[tuple[str, str]]
    unnumbered_sections: int
    subsections: list[tuple[str, str]]
    titles: list[str]
    divisions: list[str]
    quoted_blocks: int

    def counts(self) -> dict[str, int]:
        return {
            "section": len(self.sections),
            "unnumberedSection": self.unnumbered_sections,
            "subsection": len(self.subsections),
            "title": len(self.titles),
            "division": len(self.divisions),
            "quotedBlock": self.quoted_blocks,
        }


def _section_number(node: Any) -> str:
    """A section node's number as ``Sec.`` reads it, with any trailing period stripped."""
    match = _SECTION_NUMBER.match(node.section_number or "")
    return (match[1] if match else node.section_number or "").rstrip(".")


def xml_structure(document: BillDocument) -> XmlStructure:
    """What the engine's own nodes say the document holds, in the same keys the HTML rules produce."""
    sections: list[tuple[str, str]] = []
    unnumbered = 0
    subsections: list[tuple[str, str]] = []
    titles: dict[tuple[str, str], None] = {}
    divisions: dict[str, None] = {}
    for node in document.sections:
        if node.tag == "section":
            number = _section_number(node)
            if number:
                sections.append((number, " ".join(node.header_text.split())))
            else:
                unnumbered += 1
        elif node.tag == "subsection":
            enum = _ENUM.match(node.display_path[-1] if node.display_path else "")
            if enum:
                subsections.append((_section_number(node), enum[1]))
        for label in node.display_path[:-1]:
            if _TITLE_LABEL.match(label):
                titles.setdefault((node.division_label, label))
        if node.division_label:
            divisions.setdefault(node.division_label)
    title_enums = [m[1] for _, label in titles if (m := _TITLE_LABEL.match(label))]
    division_enums = [m[1] for label in divisions if (m := _DIVISION_LABEL.match(label))]
    return XmlStructure(
        sections, unnumbered, subsections, title_enums, division_enums, document.element_counts.get("quoted-block", 0)
    )


#: Elements whose text the reconstruction has to place somewhere, whether the
#: DTD requires them (``form``'s children) or only permits them
#: (``metadata/dublinCore``). Read from the document, so an element a file does
#: not carry is never scored.
_FRONT_MATTER_PARENTS = ("form", "metadata")
#: Attributes that are identifiers or rendering instructions rather than text.
#: A print rendition has no place to put any of them, which is what makes them
#: the profile's generated-value problem.
IDENTIFIER_ATTRIBUTES = (
    "id",
    "dms-id",
    "name-id",
    "committee-id",
    "bill-type",
    "public-private",
    "key",
    "style",
    "display",
    "display-inline",
    "date",
    "section-type",
)


def _contains(haystack: Sequence[str], needle: Sequence[str]) -> bool:
    """Whether the normalized word sequence appears contiguously; ``O(len(haystack))`` per call."""
    if not needle:
        return False
    # Hoisted: comparing against a list built once per call, not once per
    # candidate position.
    wanted = list(needle)
    first, span = wanted[0], len(wanted)
    return any(
        haystack[index : index + span] == wanted
        for index, word in enumerate(haystack)
        if word == first and index + span <= len(haystack)
    )


def front_matter_coverage(xml_bytes: bytes, html_words: Sequence[str]) -> dict[str, bool]:
    """For each front-matter element the XML carries, whether the HTML prints its words.

    The test is one-directional on purpose and says so: finding the words in the
    print proves the reconstruction *could* place them, not that a rule would
    pick the right span. Not finding them proves the print does not carry the
    element at all, which is the direction that decides what has to be marked
    generated.
    """
    root = parse_xml(
        xml_bytes, max_bytes=BODY_MAX_BYTES, error_type=ProbeError, label="bill XML", allow_external_doctype=True
    )
    found: dict[str, bool] = {}
    for parent_tag in _FRONT_MATTER_PARENTS:
        for parent in root.iter(parent_tag):
            for element in parent.iter():
                if element is parent:
                    continue
                words = normalized_words("".join(element.itertext()))
                if words:
                    name = local_name(element.tag)
                    found[name] = found.get(name, False) or _contains(html_words, words)
    return found


def identifier_coverage(xml_bytes: bytes, html_text: str) -> dict[str, dict[str, int]]:
    """Distinct values of each identifier attribute, and how many appear anywhere in the print."""
    root = parse_xml(
        xml_bytes, max_bytes=BODY_MAX_BYTES, error_type=ProbeError, label="bill XML", allow_external_doctype=True
    )
    values: dict[str, set[str]] = {}
    for element in root.iter():
        for name, value in element.attrib.items():
            if local_name(name) in IDENTIFIER_ATTRIBUTES and value:
                values.setdefault(local_name(name), set()).add(value)
    return {
        name: {"distinct": len(found), "inHtml": sum(1 for value in found if value in html_text)}
        for name, found in sorted(values.items())
    }


def xml_body_text(xml_bytes: bytes) -> str:
    """The body elements' text, one chunk per line so a header never runs into the text after it."""
    root = parse_xml(
        xml_bytes, max_bytes=BODY_MAX_BYTES, error_type=ProbeError, label="bill XML", allow_external_doctype=True
    )
    return "\n".join(chunk for tag in _XML_BODIES for body in root.iter(tag) for chunk in body.itertext())


# --- scoring ------------------------------------------------------------------------------


def agreement(matched: int, found: int, reference: int) -> dict[str, Any]:
    """Precision is of what the rules found, recall of what the XML holds; ``None`` where there is nothing to divide."""
    return {
        "html": found,
        "xml": reference,
        "matched": matched,
        "precision": round(matched / found, 4) if found else None,
        "recall": round(matched / reference, 4) if reference else None,
    }


def precision_recall(found: Sequence[Any], reference: Sequence[Any]) -> dict[str, Any]:
    """Multiset agreement on the key, so a repeated enumerator pairs only as often as both sides carry it."""
    return agreement(sum((Counter(found) & Counter(reference)).values()), len(found), len(reference))


def _header_agreement(html: HtmlStructure, xml: XmlStructure) -> dict[str, int]:
    """Among sections paired by number, whether the two renditions spell the catchline the same.

    Split in two, because an agreement of ``""`` against ``""`` is not evidence
    that a catchline was recovered. An appropriations run-in heading carries no
    catchline in *either* rendition, so it agrees trivially; counting those
    beside real agreements inflates the figure with the very shape that has
    nothing to compare. ``comparedWithCatchline`` is the number where at least
    one side spells one, and it is the only one worth reading as a score.
    """
    xml_headers: dict[str, list[str]] = {}
    for number, header in xml.sections:
        xml_headers.setdefault(number, []).append(" ".join(normalized_words(header)))
    agreed = compared = empty = 0
    for number, header in html.sections:
        candidates = xml_headers.get(number)
        if not candidates:
            continue
        spelled = " ".join(normalized_words(header))
        if not spelled and not any(candidates):
            empty += 1
            continue
        compared += 1
        agreed += spelled in candidates
    return {"comparedWithCatchline": compared, "agreed": agreed, "comparedEmpty": empty}


#: What each rule saw beyond its own count, so a number in the tables can be
#: traced to the print convention that produced it.
OBSERVATIONS = (
    ("runinSections", "a run-in `Sec. n.` heading at the appropriations indent"),
    ("struckSections", "a heading inside GPO's `<DELETED>` markers (a reported bill's struck text)"),
    ("tocEntries", "a table-of-contents entry at column 0, excluded from every count"),
    ("tocBanners", "a TITLE or DIVISION banner inside a contents list, excluded"),
    ("quoteTerms", "a quote-opening line with no `:` lead-in, read as an inline term, not a block"),
    ("romanSubsections", "a subsection the indent rule kept that an enumerator-only rule calls a roman lookalike"),
    ("inlineEnumHeadings", "a subsection opening on its section's own heading line"),
)


def _observations(html: HtmlStructure) -> dict[str, int]:
    return {
        "runinSections": html.runin_sections,
        "struckSections": html.struck_sections,
        "tocEntries": html.toc_entries,
        "tocBanners": html.toc_banners,
        "quoteTerms": html.quote_terms,
        "romanSubsections": html.roman_subsections,
        "inlineEnumHeadings": html.inline_enum_headings,
    }


def struck_expected(document: BillDocument, html: HtmlStructure) -> bool:
    """Whether the print's struck-text marker held for a document that carries two bodies.

    The lower bound this exists for: ``<DELETED>`` is a print convention read
    off this corpus, not a DTD element, and it reaches the rules only because
    the ``htm`` rendition escapes it into text. If GPO stopped escaping it, or
    renamed it, ``struck_sections`` would fall silently to zero and the
    measurement would still report a clean score -- the failure would look
    exactly like a document that simply has no struck text. So a document whose
    XML carries more than one body must show the marker, and a run where this
    is ``False`` anywhere is reported rather than averaged away.
    """
    return len(document.body_tags) < 2 or html.struck_sections > 0


def measure_pair(package_id: str, xml_bytes: bytes, html_bytes: bytes) -> dict[str, Any]:
    """Everything one paired document yields; no request, no file."""
    identity = parse_package_id(package_id)
    document = parse_bill_tree(xml_bytes, version=identity.version or "")
    xml_text = rendition_text(xml_bytes, rendition="xml").text
    html_text = rendition_text(html_bytes, rendition="htm").text
    html = scan_html(html_text)
    xml = xml_structure(document)
    html_words = normalized_words(html_text)
    html_lines = html_text.split("\n")
    body_start = html.body_start
    body_html = "\n".join(html_lines[body_start:])
    tags = sorted({event.name for event in read_html_events(html_bytes).events if event.kind in ("start", "empty")})
    return {
        "packageId": package_id,
        "bodies": len(document.body_tags),
        "struckExpected": struck_expected(document, html),
        "congress": identity.congress,
        "billType": identity.document_type,
        "version": identity.version,
        "stage": document.stage,
        "rootTag": document.root_tag,
        "xmlBytes": len(xml_bytes),
        "htmlBytes": len(html_bytes),
        "xmlSha256": hashlib.sha256(xml_bytes).hexdigest(),
        "htmlSha256": hashlib.sha256(html_bytes).hexdigest(),
        "fidelity": fidelity(html_words, normalized_words(xml_text)),
        "bodyFidelity": fidelity(normalized_words(body_html), normalized_words(xml_body_text(xml_bytes))),
        "frontMatter": front_matter_coverage(xml_bytes, html_words),
        "identifiers": identifier_coverage(xml_bytes, html_text),
        "structure": {
            "section": precision_recall([n for n, _ in html.sections], [n for n, _ in xml.sections]),
            "subsection": precision_recall(html.subsections, xml.subsections),
            "title": precision_recall(html.titles, xml.titles),
            "division": precision_recall(html.divisions, xml.divisions),
            # Quoted blocks have no enumerator to pair on, so this is agreement
            # of counts: it cannot see one block found where another was missed.
            "quotedBlock": agreement(min(html.quoted_blocks, xml.quoted_blocks), html.quoted_blocks, xml.quoted_blocks),
        },
        "headerAgreement": _header_agreement(html, xml),
        "sequence": sequence_check([n for n, _ in html.sections]),
        "unnumberedSections": xml.unnumbered_sections,
        "observations": _observations(html),
        "banners": html.banners,
        "markers": html.markers,
        "htmlTags": tags,
        "xmlElements": dict(document.element_counts),
        "discardedElements": dict(document.discarded_elements),
    }


def measure_html_only(package_id: str, html_bytes: bytes) -> dict[str, Any]:
    """One pre-113th HTML body's structure counts, sequence check and markers, with no XML to score against."""
    identity = parse_package_id(package_id)
    html = scan_html(rendition_text(html_bytes, rendition="htm").text)
    return {
        "packageId": package_id,
        "congress": identity.congress,
        "billType": identity.document_type,
        "version": identity.version,
        "htmlBytes": len(html_bytes),
        "htmlSha256": hashlib.sha256(html_bytes).hexdigest(),
        "structure": html.counts(),
        "sequence": sequence_check([n for n, _ in html.sections]),
        "observations": _observations(html),
        "banners": html.banners,
        "markers": html.markers,
    }


# --- aggregates ------------------------------------------------------------------------

KINDS = ("section", "subsection", "title", "division", "quotedBlock")


def aggregate(paired: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    """The corpus-wide structure, fidelity, inventory, front-matter and identifier aggregates."""
    out: dict[str, Any] = {"documents": len(paired), "structure": {}, "fidelity": {}, "inventory": {}}
    for kind in KINDS:
        rows = [doc["structure"][kind] for doc in paired]
        html, xml, matched = (sum(row[key] for row in rows) for key in ("html", "xml", "matched"))
        precisions = [row["precision"] for row in rows if row["precision"] is not None]
        recalls = [row["recall"] for row in rows if row["recall"] is not None]
        out["structure"][kind] = {
            "html": html,
            "xml": xml,
            "matched": matched,
            "microPrecision": round(matched / html, 4) if html else None,
            "microRecall": round(matched / xml, 4) if xml else None,
            "macroPrecision": round(statistics.fmean(precisions), 4) if precisions else None,
            "macroRecall": round(statistics.fmean(recalls), 4) if recalls else None,
            "documentsWithKind": sum(1 for row in rows if row["xml"]),
            "documentsExact": sum(1 for row in rows if row["html"] == row["xml"] == row["matched"] and row["xml"]),
        }
    for key in ("fidelity", "bodyFidelity"):
        ratios = [doc[key]["ratio"] for doc in paired]
        html_only: Counter[str] = Counter()
        xml_only: Counter[str] = Counter()
        for doc in paired:
            html_only.update(dict(doc[key]["htmlOnly"]["top"]))
            xml_only.update(dict(doc[key]["xmlOnly"]["top"]))
        out["fidelity"][key] = {
            "mean": round(statistics.fmean(ratios), 4) if ratios else None,
            "median": round(statistics.median(ratios), 4) if ratios else None,
            "min": min(ratios) if ratios else None,
            "htmlOnlyTop": html_only.most_common(20),
            "xmlOnlyTop": xml_only.most_common(20),
        }
    headers = [doc["headerAgreement"] for doc in paired]
    out["headerAgreement"] = {
        key: sum(row[key] for row in headers) for key in ("comparedWithCatchline", "agreed", "comparedEmpty")
    }
    present: Counter[str] = Counter()
    discarded: Counter[str] = Counter()
    for doc in paired:
        present.update({local_name(tag) for tag in doc["xmlElements"]})
        discarded.update({local_name(tag) for tag, count in doc["discardedElements"].items() if count})
    out["unnumberedSections"] = sum(doc["unnumberedSections"] for doc in paired)
    out["multiBodyDocuments"] = sum(1 for doc in paired if doc["bodies"] > 1)
    out["struckMarkerHeld"] = [doc["packageId"] for doc in paired if not doc["struckExpected"]]
    out["observations"] = {name: sum(doc["observations"][name] for doc in paired) for name, _ in OBSERVATIONS}
    carried: Counter[str] = Counter()
    printed: Counter[str] = Counter()
    for doc in paired:
        for name, in_html in doc["frontMatter"].items():
            carried[name] += 1
            printed[name] += in_html
    out["frontMatter"] = {
        name: {"documents": carried[name], "inHtml": printed[name]}
        for name in sorted(carried, key=lambda n: -carried[n])
    }
    identifiers: dict[str, dict[str, int]] = {}
    for doc in paired:
        for name, counts in doc["identifiers"].items():
            row = identifiers.setdefault(name, {"documents": 0, "distinct": 0, "inHtml": 0})
            row["documents"] += 1
            row["distinct"] += counts["distinct"]
            row["inHtml"] += counts["inHtml"]
    out["identifiers"] = dict(sorted(identifiers.items(), key=lambda item: -item[1]["distinct"]))
    out["inventory"] = {
        "xmlElementsByDocuments": dict(present.most_common()),
        "discardedByDocuments": dict(discarded.most_common()),
        "htmlTags": sorted({tag for doc in paired for tag in doc["htmlTags"]}),
        "bannerLines": {str(n): count for n, count in sorted(Counter(len(doc["banners"]) for doc in paired).items())},
        "markers": dict(sum((Counter(doc["markers"]) for doc in paired), Counter())),
    }
    return out


_DTD_ELEMENT = re.compile(r"<!ELEMENT\s+(bill|form|metadata|dublinCore|legis-body|section)\s+(.*?)>", re.DOTALL)
_DTD_ENTITY = re.compile(r"<!ENTITY\s+%\s+form-model\s+\"(.*?)\"", re.DOTALL)
_DTD_PARTICLE = re.compile(r"([A-Za-z][\w:.-]*)\s*([?*+]?)")


def dtd_content_models(dtd: str | None) -> dict[str, str]:
    """The content models the profile has to satisfy, as the DTD spells them."""
    if not dtd:
        return {}
    return {name: " ".join(model.split()) for name, model in _DTD_ELEMENT.findall(dtd)}


def dtd_form_particles(dtd: str | None) -> dict[str, bool]:
    """Each ``<form>`` child the DTD names, and whether it is required there.

    Read from the DTD's own ``%form-model;`` entity rather than from a list
    kept here, so the requirement the profile must satisfy is the publisher's
    statement and moves when the publisher's does.
    """
    entity = _DTD_ENTITY.search(dtd or "")
    if entity is None:
        return {}
    return {name: occurrence not in ("?", "*") for name, occurrence in _DTD_PARTICLE.findall(entity[1])}


# --- rendering -----------------------------------------------------------------------------


def _pct(value: float | None) -> str:
    """A ratio as a one-decimal percent, or an em dash when there is no denominator."""
    return "—" if value is None else f"{value * 100:.1f}%"


def _pr(row: Mapping[str, Any]) -> str:
    """One structure cell as ``matched/found in HTML/in XML``."""
    return f"{row['matched']}/{row['html']}/{row['xml']}"


def _words(pairs: Sequence[Sequence[Any]], limit: int = 12) -> str:
    """``word×count`` pairs as backticked markdown, or an em dash when there are none."""
    return ", ".join(f"`{word}`×{count}" for word, count in pairs[:limit]) or "—"


def _structure_table(agg: Mapping[str, Any]) -> list[str]:
    """The per-kind precision/recall markdown table for one aggregate."""
    lines = [
        "| Kind | Found in HTML | In XML | Matched | Micro precision | Micro recall | Macro precision | Macro recall | Docs with kind | Docs exact |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for kind in KINDS:
        row = agg["structure"][kind]
        lines.append(
            f"| {kind} | {row['html']} | {row['xml']} | {row['matched']} | {_pct(row['microPrecision'])} | "
            f"{_pct(row['microRecall'])} | {_pct(row['macroPrecision'])} | {_pct(row['macroRecall'])} | "
            f"{row['documentsWithKind']} | {row['documentsExact']} |"
        )
    return lines


def _held_out_block(measures: Mapping[str, Any]) -> list[str]:
    """The untuned score, which leads, and the documents it was drawn from."""
    held = measures.get("heldOut")
    if not held or not held.get("paired"):
        return [
            "",
            "### Held-out score",
            "",
            (
                "**Not measured.** Every figure below is in-sample: the rules were revised against these same "
                "documents, so they are an upper bound, not an expected score on unseen bills."
            ),
        ]
    agg = held.get("aggregate") or aggregate(held["paired"])
    selection = held.get("selection", {})
    fidelity_row = agg["fidelity"]["bodyFidelity"]
    return [
        "",
        "### Held-out score: the rules on documents they were never revised against",
        "",
        (
            f"**This is the headline.** {len(held['paired'])} documents drawn from the same five listings at "
            f"disjoint quantiles {tuple(selection.get('quantiles', ()))}, with every tuning document excluded by "
            "package id, and scored once after the rules were frozen. The in-sample table further down is the "
            "upper bound; this is the number to plan against."
        ),
        "",
        *_structure_table(agg),
        "",
        (
            f"Body text fidelity on the held-out corpus: {_pct(fidelity_row['mean'])} mean, "
            f"{_pct(fidelity_row['median'])} median, {_pct(fidelity_row['min'])} worst. Catchlines agreeing: "
            f"{agg['headerAgreement']['agreed']} of {agg['headerAgreement']['comparedWithCatchline']} "
            f"(+{agg['headerAgreement']['comparedEmpty']} where neither rendition spells one)."
        ),
        "",
        "Held-out documents: " + ", ".join(f"`{d['packageId']}`" for d in held["paired"]) + ".",
        *(
            [
                "",
                "Refused or unavailable in the held-out draw: "
                + "; ".join(f"`{r['packageId']}` ({r['reason']})" for r in held["refused"]),
            ]
            if held.get("refused")
            else []
        ),
    ]


def render(measures: Mapping[str, Any]) -> str:
    """The whole generated markdown block for one measurement sidecar, markers included."""
    paired = measures.get("paired", [])
    pre = measures.get("pre113", [])
    agg = measures.get("aggregate") or aggregate(paired)
    requests = measures.get("requests", {})
    held = measures.get("heldOut") or {}
    lines = [
        MARK_START,
        "",
        (
            f"Measured {measures.get('generatedAt', '')[:10]} by `tools/analysis/bill_html_xml_gap.py` at spicy-docs "
            f"`{measures.get('revision', 'unknown')}`; "
            f"{requests.get('cumulative', requests.get('total', 0))} publisher requests across every run that built "
            f"this corpus (the request log reconciles that figure with the cache hits and the per-process "
            f"{MAX_REQUESTS}-request bound), {len(paired)} tuning documents, "
            f"{len(held.get('paired', []))} held-out documents, {len(pre)} pre-113th HTML bodies. "
            "Per-kind cells read `matched/found in HTML/in XML`. The command, the run's full output and every "
            f"document's digest are retained outside this repository in `{RECEIPTS}`; this document's sidecar "
            "`bill-html-xml-gap-2026-09-19.json` is the committed pin."
        ),
        *_held_out_block(measures),
        "",
        "### Tuning corpus: fidelity and structure per document",
        "",
        (
            "**In-sample.** The rules were revised against these thirty documents until they stopped losing "
            "structure, so what follows is an upper bound on the rules' accuracy, not an estimate of their "
            "accuracy on unseen bills. The held-out table above is the untuned score."
        ),
        "",
        "| Package | Stage | XML B | HTML B | Ratio | Body ratio | HTML-only | XML-only | Sections | Unnum. | Subsections | Titles | Divisions | Quoted | Catchlines agree (+neither) |",
        "|---|---|---:|---:|---:|---:|---:|---:|---|---:|---|---|---|---|---|",
    ]
    for doc in paired:
        s = doc["structure"]
        lines.append(
            f"| `{doc['packageId']}` | {doc['version']} | {doc['xmlBytes']:,} | {doc['htmlBytes']:,} | "
            f"{_pct(doc['fidelity']['ratio'])} | {_pct(doc['bodyFidelity']['ratio'])} | "
            f"{doc['fidelity']['htmlOnly']['count']} | {doc['fidelity']['xmlOnly']['count']} | "
            f"{_pr(s['section'])} | {doc['unnumberedSections']} | {_pr(s['subsection'])} | {_pr(s['title'])} | "
            f"{_pr(s['division'])} | {_pr(s['quotedBlock'])} | "
            f"{doc['headerAgreement']['agreed']}/{doc['headerAgreement']['comparedWithCatchline']}"
            f" (+{doc['headerAgreement']['comparedEmpty']}) |"
        )
    lines += [
        "",
        "### Structure recovered by rule, over the tuning corpus (in-sample)",
        "",
        *_structure_table(agg),
    ]
    inv = agg["inventory"]
    header = agg["headerAgreement"]
    lines += [
        "",
        (
            f"Catchlines that read the same once casefolded: {header['agreed']} of "
            f"{header['comparedWithCatchline']} sections where at least one rendition spells one, plus "
            f"{header['comparedEmpty']} sections where neither does (an appropriations run-in heading carries no "
            f"catchline in either rendition, so it agrees trivially and is counted apart). Body `<section>` elements "
            f"the XML carries with no `<enum>`, which print with no heading and so are held out of the section "
            f"denominator: {agg['unnumberedSections']}."
        ),
        "",
        "What each rule saw, over the paired corpus:",
        "",
        "| Observation | Count |",
        "|---|---:|",
    ]
    lines += [f"| {label} | {agg['observations'][name]} |" for name, label in OBSERVATIONS]
    lines += [
        "",
        "### Text fidelity",
        "",
        "| Scope | Mean ratio | Median | Min | Words only the HTML has (top) | Words only the XML has (top) |",
        "|---|---:|---:|---:|---|---|",
    ]
    for key, label in (("fidelity", "whole document"), ("bodyFidelity", "body only")):
        row = agg["fidelity"][key]
        lines.append(
            f"| {label} | {_pct(row['mean'])} | {_pct(row['median'])} | {_pct(row['min'])} | "
            f"{_words(row['htmlOnlyTop'])} | {_words(row['xmlOnlyTop'])} |"
        )
    lines += [
        "",
        "### Inventory: what each rendition carries",
        "",
        (
            f"HTML tags across the corpus: {', '.join(f'`{t}`' for t in inv['htmlTags'])}. Bracketed banner lines per "
            f"document: {inv['bannerLines']}. Text-only markers: {inv['markers'] or 'none'}."
        ),
        "",
        "| XML element | Documents | Engine keeps its text | Documents where dropped |",
        "|---|---:|---|---:|",
    ]
    for tag, count in inv["xmlElementsByDocuments"].items():
        dropped = inv["discardedByDocuments"].get(tag, 0)
        keeps = "no" if dropped == count else ("partly" if dropped else "yes")
        lines.append(f"| `{tag}` | {count} | {keeps} | {dropped} |")
    models = measures.get("dtdContentModels") or {}
    particles = measures.get("dtdFormParticles") or {}
    pin = measures.get("dtdPin") or {}
    if models:
        lines += ["", "### The bill DTD's content models the profile must satisfy", ""]
        if pin:
            lines += [
                (
                    f"Pinned and cited, **not validated against**: `{pin['dtdUrl']}`, {pin['dtdBytes']:,} bytes, "
                    f"sha256 `{pin['dtdSha256']}`. Schema validation of a reconstructed document is the profile's "
                    "work, not this measurement's."
                ),
                "",
            ]
        for name, model in models.items():
            lines.append(f"- `{name}`: `{model}`")
        declares = measures.get("dtdDeclaresDeleted")
        if declares is not None:
            lines += [
                "",
                (
                    f"The DTD declares an element named `DELETED`: **{'yes' if declares else 'no'}**; it declares "
                    f"`deleted-phrase`: {'yes' if measures.get('dtdDeclaresDeletedPhrase') else 'no'}. So the "
                    "`<DELETED>` marker these rules read is a GPO **print convention inferred from this corpus**, "
                    "not a documented element, and the XML states the same fact structurally as a second "
                    f"`<legis-body>`. {agg.get('multiBodyDocuments', 0)} of the paired documents carry two bodies, "
                    f"and the marker held on {'all' if not agg.get('struckMarkerHeld') else 'not all'} of them"
                    + (f" (failed: {', '.join(agg['struckMarkerHeld'])})" if agg.get("struckMarkerHeld") else "")
                    + "."
                ),
            ]
    front = agg.get("frontMatter") or {}
    if front:
        lines += [
            "",
            "### Front matter: what the DTD asks for and what the print carries",
            "",
            (
                "`Required` is the DTD's own `%form-model;`. `Print carries it` counts the documents whose HTML "
                "holds that element's words contiguously; it proves the words are available to place, not that a "
                "rule would choose the right span."
            ),
            "",
            "| Element | In XML | Print carries it | DTD requires it in `form` |",
            "|---|---:|---:|---|",
        ]
        for name, row in front.items():
            required = particles.get(name)
            mark = "—" if required is None else ("required" if required else "optional")
            lines.append(f"| `{name}` | {row['documents']} | {row['inHtml']} | {mark} |")
    identifiers = agg.get("identifiers") or {}
    if identifiers:
        lines += [
            "",
            "Identifiers and rendering attributes, which a print rendition has nowhere to put:",
            "",
            "| Attribute | Documents | Distinct values | Found in the print |",
            "|---|---:|---:|---:|",
        ]
        for name, row in identifiers.items():
            lines.append(f"| `{name}` | {row['documents']} | {row['distinct']} | {row['inHtml']} |")
    lines += [
        "",
        "### Pre-113th HTML: the same rules with no XML reference",
        "",
        "| Package | Congress | Bytes | Sections | Run-in | Non-incr. | Dup. | Subsections | Titles | Divisions | Quoted | TOC entries | TOC banners | Banners | Markers |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for doc in pre:
        s, o = doc["structure"], doc["observations"]
        lines.append(
            f"| `{doc['packageId']}` | {doc['congress']} | {doc['htmlBytes']:,} | {s['section']} | "
            f"{o['runinSections']} | {doc['sequence']['nonIncreasing']} | {doc['sequence']['duplicates']} | "
            f"{s['subsection']} | {s['title']} | {s['division']} | {s['quotedBlock']} | {o['tocEntries']} | "
            f"{o['tocBanners']} | {len(doc['banners'])} | {doc['markers'] or '—'} |"
        )
    refused = measures.get("refused", [])
    if refused:
        lines += ["", "Refused or unavailable: " + "; ".join(f"`{r['packageId']}` ({r['reason']})" for r in refused)]
    lines += ["", MARK_END]
    return "\n".join(lines)


def rewrite_doc(path: Path, block: str) -> None:
    """Replace the text between the marker comments in the research document; exits if a marker is missing."""
    text = path.read_text()
    start, end = text.find(MARK_START), text.find(MARK_END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit(f"{path} lacks the generated-block markers")
    path.write_text(text[:start] + block + text[end + len(MARK_END) :])


# --- main ------------------------------------------------------------------------------------


def _revision(root: Path) -> str:
    """The short HEAD hash of the repo at ``root``, or ``"unknown"`` outside git."""
    result = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], cwd=root, capture_output=True, text=True, check=False
    )
    return result.stdout.strip() or "unknown"


def _refusal(package_id: str, error: Exception, api_key: str) -> dict[str, str]:
    """A refusal kept as evidence, with the credential scrubbed before it is truncated.

    Order matters and is the reason this is one function rather than an inline
    f-string: truncating first can cut a key in half and leave its front
    standing, which is exactly what ``scrub_credential``'s own docstring warns
    about.
    """
    return {"packageId": package_id, "reason": scrub_credential(f"{type(error).__name__}: {error}", api_key)[:200]}


def _parse_listing(value: str) -> tuple[int, int, str]:
    """``CONGRESS:SESSION:TYPE`` as the bulk route spells it."""
    parts = value.split(":")
    if len(parts) != 3 or not parts[0].isdigit() or not parts[1].isdigit() or not parts[2].isalpha():
        raise ValueError(f"listing must be CONGRESS:SESSION:TYPE, not {value!r}")
    return int(parts[0]), int(parts[1]), parts[2]


def measure(
    cache: Path,
    api_key: str,
    *,
    timeout: float,
    interval: float,
    selection: Selection = SELECTION,
    exclude: frozenset[str] = frozenset(),
    pre113: bool = True,
) -> dict[str, Any]:
    """One corpus drawn under ``selection`` and scored; ``exclude`` keeps a held-out draw disjoint."""
    measures: dict[str, Any] = {"paired": [], "pre113": [], "refused": []}
    budget = PagedJsonBudget(
        max_requests=3, max_page_bytes=4 * 1024 * 1024, timeout_seconds=timeout, min_request_interval_seconds=interval
    )
    with (
        KeylessProbe(timeout_seconds=timeout, min_request_interval_seconds=interval) as probe,
        CongressListingReader(budget=budget, api_key=api_key) as congress,
    ):
        pairs: list[str] = []
        for congress_number, session, bill_type in selection.listings:
            listing = fetch_listing(probe, cache, congress_number, session, bill_type)
            pairs.extend(select_pairs(listing, selection, exclude=exclude | frozenset(pairs)))
        measures["selection"] = {**asdict(selection), "pairs": pairs, "excluded": sorted(exclude)}
        for package_id in pairs:
            try:
                xml_bytes = fetch_body(probe, cache, package_id, "xml")
                html_bytes = fetch_body(probe, cache, package_id, "htm")
                measures["paired"].append(measure_pair(package_id, xml_bytes, html_bytes))
                print(f"paired {package_id}: {measures['paired'][-1]['fidelity']['ratio']}", file=sys.stderr)
            except (ProbeError, ValueError, RequestBudgetExhausted) as error:
                measures["refused"].append(_refusal(package_id, error, api_key))
                print(f"refused {package_id}: {error}", file=sys.stderr)
        if not pre113:
            measures["aggregate"] = aggregate(measures["paired"])
            return measures
        pre_ids: list[str] = list(PRE_113_PROVEN)
        for congress_number, bill_type, number in PRE_113_LOOKUPS:
            try:
                stated = stated_package_id(fetch_text_versions(congress, cache, congress_number, bill_type, number))
            except (ProbeError, ValueError, RequestBudgetExhausted) as error:
                measures["refused"].append(_refusal(f"{congress_number} {bill_type} {number}", error, api_key))
                continue
            if stated:
                pre_ids.append(stated)
            else:
                measures["refused"].append(
                    {"packageId": f"{congress_number} {bill_type} {number}", "reason": "no stated BILLS package id"}
                )
        measures["selection"]["pre113"] = pre_ids
        for package_id in pre_ids:
            try:
                measures["pre113"].append(measure_html_only(package_id, fetch_body(probe, cache, package_id, "htm")))
            except (ProbeError, ValueError, RequestBudgetExhausted) as error:
                measures["refused"].append(_refusal(package_id, error, api_key))
        dtd = fetch_dtd(probe, cache)
        measures["dtdContentModels"] = dtd_content_models(dtd.text if dtd else None)
        measures["dtdFormParticles"] = dtd_form_particles(dtd.text if dtd else None)
        measures["dtdPin"] = dtd.pin() if dtd else {}
        # Recorded, not assumed: the print marker this tool reads is not a DTD
        # element, and saying so needs the schema in hand.
        measures["dtdDeclaresDeleted"] = dtd_declares(dtd, "DELETED")
        measures["dtdDeclaresDeletedPhrase"] = dtd_declares(dtd, "deleted-phrase")
    measures["aggregate"] = aggregate(measures["paired"])
    return measures


def main(argv: list[str] | None = None) -> int:
    """Draw and score the selected corpus, merge a held-out score, then rewrite the document; 1 on refusal."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--output", type=Path, required=True, help="measurement JSON; read instead of measured with --offline"
    )
    parser.add_argument(
        "--doc", type=Path, required=True, help="the research document whose generated block is rewritten"
    )
    parser.add_argument("--cache", type=Path, help="where fetched bytes live; reused on a rerun")
    parser.add_argument("--env-file", type=Path, help="file holding the api.data.gov key")
    parser.add_argument("--env-var", default="API_GOV")
    parser.add_argument("--offline", action="store_true")
    parser.add_argument(
        "--selection",
        choices=sorted(SELECTIONS),
        default="tuning",
        help=(
            "which corpus to draw: 'tuning' is the one the rules were revised against; 'held-out' takes the same "
            "listings at disjoint quantiles, excluding every tuning document, and is merged into the sidecar's "
            "heldOut block without disturbing the tuning measurement"
        ),
    )
    parser.add_argument(
        "--quantiles",
        type=float,
        nargs="+",
        help="override the selection's quantiles, e.g. --quantiles 0.25 0.75",
    )
    parser.add_argument(
        "--listings",
        nargs="+",
        metavar="CONGRESS:SESSION:TYPE",
        help="override the selection's bulk listings, e.g. --listings 113:1:hr 114:2:s",
    )
    parser.add_argument("--min-interval-seconds", type=float, default=0.3)
    parser.add_argument("--timeout", type=float, default=60.0)
    args = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[2]
    if args.offline:
        measures = json.loads(args.output.read_text())
    else:
        if args.env_file is None or args.cache is None:
            parser.error("--env-file and --cache are required unless --offline")
        api_key = read_api_key(args.env_file, args.env_var)
        held_out = args.selection == "held-out"
        selection = SELECTIONS[args.selection]
        if args.quantiles:
            selection = replace(selection, quantiles=tuple(args.quantiles))
        if args.listings:
            try:
                listings = tuple(_parse_listing(value) for value in args.listings)
            except ValueError as error:
                parser.error(str(error))
            selection = replace(selection, listings=listings)
        saved = json.loads(args.output.read_text()) if args.output.exists() else {}
        # A held-out draw must not be able to re-score a tuning document. The
        # exclusion is the saved run's own package ids, so it is the measured
        # corpus that is excluded, not a list kept in step with it by hand.
        exclude = frozenset(document["packageId"] for document in saved.get("paired", [])) if held_out else frozenset()
        if held_out and not exclude:
            parser.error("--selection held-out needs an existing measurement to exclude; run the tuning draw first")
        try:
            drawn = measure(
                args.cache,
                api_key,
                timeout=args.timeout,
                interval=args.min_interval_seconds,
                selection=selection,
                exclude=exclude,
                pre113=not held_out,
            )
        except CredentialRefusedError as error:
            print(f"credential refused; stopping: {scrub_credential(str(error), api_key)}", file=sys.stderr)
            return 1
        if held_out:
            overlap = exclude & {document["packageId"] for document in drawn["paired"]}
            if overlap:
                raise SystemExit(f"held-out draw overlaps the tuning corpus: {', '.join(sorted(overlap))}")
            measures = saved
            measures["heldOut"] = drawn
        else:
            measures = drawn
            # A re-drawn tuning corpus invalidates a held-out block measured
            # against the previous one.
            if saved.get("heldOut") and [d["packageId"] for d in saved["paired"]] == [
                d["packageId"] for d in drawn["paired"]
            ]:
                measures["heldOut"] = saved["heldOut"]
        measures["generatedAt"] = datetime.now(UTC).isoformat()
        measures["revision"] = _revision(root)
        # A rerun against a full cache makes no request, which would report a
        # corpus that cost nothing. The cumulative figure is what the
        # measurement actually spent at the publisher, and it is the one the
        # document states.
        previous = json.loads(args.output.read_text()).get("requests", {}) if args.output.exists() else {}
        measures["requests"] = {
            **REQUESTS,
            "total": sum(REQUESTS.values()),
            "cumulative": int(previous.get("cumulative") or previous.get("total") or 0) + sum(REQUESTS.values()),
        }
        text = json.dumps(measures, indent=2, sort_keys=True) + "\n"
        if api_key in text or "api_key=" in text or "X-Api-Key" in text:
            raise SystemExit("refusing to write a sidecar that carries a credential")
        args.output.write_text(text)
        # Render from the bytes just written, so a later --offline run and the
        # fixture test produce the same block from the same JSON shapes.
        measures = json.loads(text)
    rewrite_doc(args.doc, render(measures))
    print(json.dumps({"output": str(args.output), "doc": str(args.doc), "requests": measures.get("requests")}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
