"""Measure the legislative-branch data map: what each route lists, from when, and how big.

One bounded pass over three machine-readable inventories plus a fixed set of
publisher samples, then the map's tables are rewritten from those measurements
and the judgments held in ``ROWS`` below. Judgments (status, note) are data
here so that a status can never cite a module that does not exist: every
``have`` and ``port`` row names evidence paths and the run refuses if one is
missing. Run from the repository root:

  uv run --frozen python -m tools.analysis.legislative_data_map \\
      --env-file .env --output docs/research/legislative-data-map-2026-09-18.json \\
      --map docs/research/legislative-data-map-2026-09-18.md

``--offline`` rewrites the tables from an existing output without the network.

Measurements, and what each cannot see:

* Congress.gov: one ``limit=1`` request per collection route for its declared
  total, then a descent by Congress (or volume) until two empty Congresses
  follow a populated one, or the cap. The earliest populated Congress is a
  lower bound on coverage; a gap wider than one Congress would hide older
  material and the cap is reported when it ends the walk.
* GovInfo: the ``collections`` inventory for package counts; for named
  collections a binary search on ``published/{year}-01-01`` for the earliest
  issue year, checked against the inventory count; the keyless bulkdata
  listing for folder ranges and top-level sizes.
* The CDTF catalog for periodicity and the caveat counts.
* One keyless sample per publisher XML or JSON candidate: media type, size,
  digest, root element and first-level children. Whether those name the
  document's own identity remains a judgment in the row note.

A credential refusal (401/403 on a keyed route) aborts the run.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections import Counter
from collections.abc import Mapping
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlencode, urlsplit

import httpx

from spicy_docs.reading.paged_json import PagedJsonBudget, PagedJsonReader, PagedJsonSourceError
from spicy_docs.reading.xml import parse_xml
from spicy_docs.sources.congress.listing import CongressListingReader
from spicy_docs.sources.govinfo.discovery import GovInfoDiscoveryReader, published_url
from spicy_docs.transport.capture import CapturedBodyResponse
from spicy_docs.transport.credentials import CredentialRefusedError, read_api_key, scrub_credential
from spicy_docs.transport.source_acquirer import SourceAcquirer

CONGRESS_API = "https://api.congress.gov/v3"
GOVINFO_API = "https://api.govinfo.gov"
GOVINFO_BULK = "https://www.govinfo.gov/bulkdata/json"
CDTF_CATALOG = "https://usgpo.github.io/innovation/data.json"
CURRENT_CONGRESS = 119
CURRENT_RECORD_VOLUME = 172
CURRENT_YEAR = 2026
FIRST_YEAR = 1789
ERROR_TOLERANCE = 6
LEADING_EMPTY_TOLERANCE = 6
JSON_TYPES = ("application/json",)
SAMPLE_MAX_BYTES = 16 * 1024 * 1024
XML_TYPES = ("text/xml", "application/xml", "application/rss+xml", "application/atom+xml")
MARK_START = "<!-- generated by tools/analysis/legislative_data_map.py: start -->"
MARK_END = "<!-- generated by tools/analysis/legislative_data_map.py: end -->"
PORT_PLAN = "docs/research/billtrax-port-2026-09-15.md"
REQUESTS: Counter[str] = Counter()


# --- what is measured ---------------------------------------------------------


@dataclass(frozen=True)
class CongressRoute:
    """One Congress.gov collection route: its list key and, when it has one, its per-Congress path."""

    route: str
    records_key: str
    descent: str | None = None
    start: int = CURRENT_CONGRESS


CONGRESS_ROUTES = (
    CongressRoute("bill", "bills", "bill/{c}"),
    CongressRoute("amendment", "amendments", "amendment/{c}"),
    CongressRoute("summaries", "summaries", "summaries/{c}"),
    CongressRoute("law", "bills", "law/{c}"),
    CongressRoute("committee-report", "reports", "committee-report/{c}"),
    CongressRoute("committee-print", "committeePrints", "committee-print/{c}"),
    CongressRoute("committee-meeting", "committeeMeetings", "committee-meeting/{c}"),
    CongressRoute("hearing", "hearings", "hearing/{c}"),
    CongressRoute("nomination", "nominations", "nomination/{c}"),
    CongressRoute("treaty", "treaties", "treaty/{c}"),
    CongressRoute("house-communication", "houseCommunications", "house-communication/{c}"),
    CongressRoute("senate-communication", "senateCommunications", "senate-communication/{c}"),
    CongressRoute("house-requirement", "houseRequirements"),
    CongressRoute("house-vote", "houseRollCallVotes", "house-vote/{c}"),
    CongressRoute("member", "members", "member/congress/{c}"),
    CongressRoute("committee", "committees", "committee/{c}"),
    CongressRoute("daily-congressional-record", "dailyCongressionalRecord", "daily-congressional-record/{c}", 172),
    CongressRoute("bound-congressional-record", "boundCongressionalRecord", "bound-congressional-record/{c}", 2020),
    CongressRoute("crsreport", "CRSReports"),
)

GOVINFO_COVERAGE = (
    "BILLS", "BILLSTATUS", "BILLSUM", "PLAW", "STATUTE", "COMPS", "CRPT", "CHRG", "CREC", "CRECB",
    "CPRT", "CDOC", "CDIR", "HMAN", "SMAN", "GOVMAN", "PAI", "CCAL", "HOB", "USCODE",
)  # fmt: skip

SAMPLES = {
    "clerk-vote": ("https://clerk.house.gov/evs/2025/roll240.xml", XML_TYPES),
    "senate-vote": ("https://www.senate.gov/legislative/LIS/roll_call_votes/vote1191/vote_119_1_00001.xml", XML_TYPES),
    "senate-nomination-feed": ("https://www.senate.gov/legislative/LIS/nominations/NomWithdrawn.xml", XML_TYPES),
    "house-memberdata": ("https://clerk.house.gov/xml/lists/MemberData.xml", XML_TYPES),
    "house-members-xml": ("https://member-info.house.gov/members.xml", XML_TYPES),
    "senate-cvc": ("https://www.senate.gov/legislative/LIS_MEMBER/cvc_member_data.xml", XML_TYPES),
    "senate-contact": ("https://www.senate.gov/general/contact_information/senators_cfm.xml", XML_TYPES),
    "senate-hearings": ("https://www.senate.gov/general/committee_schedules/hearings.xml", XML_TYPES),
    "senate-calendar": ("https://www.senate.gov/legislative/2025_schedule.xml", XML_TYPES),
    "docs-house-floor-rss": ("https://docs.house.gov/BillsThisWeek-RSS.xml", XML_TYPES),
    "lda-filings": ("https://lda.gov/api/v1/filings/?page_size=1", JSON_TYPES),
    "lda-contributions": ("https://lda.gov/api/v1/contributions/?page_size=1", JSON_TYPES),
}


# --- the judgments ------------------------------------------------------------


@dataclass(frozen=True)
class Row:
    """One map row: the judgment, the measurement it reads, and the repo evidence a claim rests on."""

    table: str
    subject: str
    data: str
    route: str
    status: str
    credential: str
    note: str
    measure: tuple[str, str] | None = None
    evidence: tuple[str, ...] = ()


KEY = "api.data.gov key"
NONE = "none"
A, B, C, D = "A", "B", "C", "D"
ROWS = (
    # Table A: Congress.gov API. One credential family, one pagination contract, one reader.
    Row(A, "bills", "Bill metadata, status, text versions", "`bill`", "have", KEY,
        "`congress/bill_acquisition.py`, `bill_status.py`, `bill_text.py`", ("congress", "bill"),
        ("src/spicy_docs/sources/congress/bill_acquisition.py", "src/spicy_docs/sources/congress/bill_status.py",
         "src/spicy_docs/sources/congress/bill_text.py")),
    Row(A, "bills", "CRS bill summaries", "`summaries`", "have", KEY,
        "a typed field of bill acquisition (`congress-bills.md:48`); the list route declared 6 records, all 119th, so it is no inventory",
        ("congress", "summaries"),
        ("docs/sources/congress-bills.md",)),
    Row(A, "bills", "Amendments listing", "`amendment`", "port 4", KEY,
        "replaces `fetchAmendments`; carry the real `amendment.status` (ledger #7)", ("congress", "amendment"), (PORT_PLAN,)),
    Row(A, "bills", "Committee-referred bills", "`committee/{chamber}/{code}/bills`", "port 4", KEY,
        "replaces `fetchCommitteeBills`", None, (PORT_PLAN,)),
    Row(A, "bills", "Amendment text", "`amendment/.../text` where present", "candidate", KEY,
        "the listing port carries no text; amendment text otherwise lives in the Record and on rules.house.gov", None),
    Row(A, "laws", "Public laws list", "`law`", "rejected", KEY,
        "bill→law numbers arrive as the bill's `laws` field; law bodies are PLAW USLM (Table B)", ("congress", "law")),
    Row(A, "votes", "Vote references on bill actions (`recordedVotes`)", "`bill/{c}/{type}/{n}/actions`", "port 4", KEY,
        "replaces `sync-roll-call-votes.ts`, which reads only these references; its 429 recursion (ledger #4) dies with it",
        None, (PORT_PLAN,)),
    Row(A, "votes", "House member-level votes", "`house-vote/{c}/{session}/{roll}/members`", "candidate", KEY,
        "not in the port plan; bioguide-keyed; names the Clerk XML as `sourceDataURL`", ("congress", "house-vote")),
    Row(A, "committees", "Committee reports", "`committee-report` (+ `/text`)", "candidate", KEY,
        "no route in either repo today; BillTrax `committee_reports` rows come only from uploads", ("congress", "committee-report")),
    Row(A, "committees", "Hearings", "`hearing`", "candidate", KEY,
        "serves `hearing_transcripts.text`, a BillTrax table nothing writes today", ("congress", "hearing")),
    Row(A, "committees", "Committee meetings (scheduled)", "`committee-meeting`", "candidate", KEY,
        "overlaps docs.house.gov and the Senate hearings calendar; API-first", ("congress", "committee-meeting")),
    Row(A, "committees", "Committee prints", "`committee-print`", "candidate", KEY, "low volume; take with reports",
        ("congress", "committee-print")),
    Row(A, "committees", "Committee rosters", "`committee`", "candidate", KEY,
        "API-first over the Clerk and Senate XML rosters", ("congress", "committee")),
    Row(A, "members", "Members", "`member`", "candidate", KEY,
        "bioguide-keyed; API-first over Bioguide bulk and the House/Senate XML", ("congress", "member")),
    Row(A, "nominations", "Nominations", "`nomination`", "candidate", KEY,
        "no coverage anywhere in the repo; API-first over the nine Senate LIS feeds", ("congress", "nomination")),
    Row(A, "treaties", "Treaties", "`treaty`", "candidate", KEY, "not previously mapped", ("congress", "treaty")),
    Row(A, "record", "Daily Congressional Record", "`daily-congressional-record`", "candidate", KEY,
        "the primary floor record; the Clerk floor summary is its digest", ("congress", "daily-congressional-record")),
    Row(A, "record", "Bound Congressional Record", "`bound-congressional-record`", "candidate", KEY,
        "historical only; take on a historical-reach need", ("congress", "bound-congressional-record")),
    Row(A, "communications", "House and Senate communications", "`house-communication`, `senate-communication`",
        "rejected", KEY, "executive communications and petitions; no consumer named", ("congress", "house-communication")),
    Row(A, "reference", "House reporting requirements", "`house-requirement`", "rejected", KEY, "no consumer named",
        ("congress", "house-requirement")),
    Row(A, "crs", "CRS report metadata and summaries", "`crsreport/{id}`", "have", KEY,
        "`crs_summaries.py`; the port plan names its query-param key (`:54`) as the legacy exception, not the pattern to clone",
        ("congress", "crsreport"),
        ("src/spicy_docs/sources/congress/crs_summaries.py", "src/spicy_docs/sources/congress/listing.py")),
    # Table B: GovInfo API and bulkdata. Discovery and MODS are collection-agnostic; bodies are per collection.
    Row(B, "bills", "BILLSTATUS bulk ZIP", "`bulkdata/BILLSTATUS`", "port 6", NONE,
        "decision 2 (bulk-scope record) first; builds on `reading/zip_archive.py`", ("govinfo", "BILLSTATUS"),
        (PORT_PLAN, "src/spicy_docs/reading/zip_archive.py")),
    Row(B, "bills", "Bill text bulk ZIP", "`bulkdata/BILLS`", "rejected", NONE,
        "derived re-export of the routes in use; revisit only as a resync optimization", ("govinfo", "BILLS")),
    Row(B, "bills", "Bill summaries bulk", "`bulkdata/BILLSUM`", "rejected", NONE,
        "CRS bill summaries already arrive as a typed bill field (Table A)", ("govinfo", "BILLSUM")),
    Row(B, "bills", "Bill PDFs", "`content/pkg/BILLS-…/pdf`", "port 5", NONE,
        "decision 1 (PDF identity semantics) first; the slug map is a sealed vocabulary (port contract)", None, (PORT_PLAN,)),
    Row(B, "laws", "Public and private laws (PLAW)", "`bulkdata/PLAW` USLM", "have", NONE, "`govinfo/uslm.py`",
        ("govinfo", "PLAW"), ("src/spicy_docs/sources/govinfo/uslm.py",)),
    Row(B, "laws", "Statute compilations (COMPS)", "`bulkdata/COMPS` USLM", "have", NONE, "`govinfo/uslm_acquisition.py`",
        ("govinfo", "COMPS"), ("src/spicy_docs/sources/govinfo/uslm_acquisition.py",)),
    Row(B, "laws", "Statutes at Large", "`bulkdata/STATUTE`", "candidate", NONE,
        "one XML per volume; the only XML route for every law before PLAW bulk begins", ("govinfo", "STATUTE")),
    Row(B, "committees", "Committee report bodies", "`CRPT` packages and granules", "candidate", KEY,
        "discovery and MODS already reach any collection; the body fetch is missing and the FR body acquisition is its template",
        ("govinfo", "CRPT"), ("src/spicy_docs/sources/govinfo/discovery.py", "src/spicy_docs/sources/govinfo/mods.py")),
    Row(B, "committees", "Hearing transcript bodies", "`CHRG`", "candidate", KEY, "same extension as CRPT", ("govinfo", "CHRG")),
    Row(B, "committees", "Committee prints, congressional documents", "`CPRT`, `CDOC`", "candidate", KEY,
        "same extension; CDOC carries treaty documents", ("govinfo", "CPRT")),
    Row(B, "record", "Congressional Record bodies", "`CREC` (daily), `CRECB` (bound)", "candidate", KEY,
        "same extension; granules are the daily sections", ("govinfo", "CREC")),
    Row(B, "reference", "Congressional Directory", "`CDIR`", "candidate", KEY, "org and staff reference; XML granules",
        ("govinfo", "CDIR")),
    Row(B, "reference", "Government Manual", "`bulkdata/GOVMAN`", "candidate", NONE, "clean org XML", ("govinfo", "GOVMAN")),
    Row(B, "reference", "House Rules and Manual", "`bulkdata/HMAN`", "candidate", NONE, "clean XML", ("govinfo", "HMAN")),
    Row(B, "reference", "Privacy Act Issuances", "`bulkdata/PAI`", "rejected", NONE, "biennial SOR descriptions; no consumer",
        ("govinfo", "PAI")),
    Row(B, "reference", "Congressional Pictorial Directory", "GovInfo collection", "rejected", KEY, "Bioguide and `member` cover it"),
    Row(B, "reference", "MODS, PREMIS, discovery", "`packages`, `granules`, `published`, `collections`", "have", KEY,
        "`govinfo/mods.py`, `premis.py`, `discovery.py`", None,
        ("src/spicy_docs/sources/govinfo/mods.py", "src/spicy_docs/sources/govinfo/premis.py",
         "src/spicy_docs/sources/govinfo/discovery.py")),
    Row(B, "committees", "House committee activity reports", "search over doctype `HRPT`; CHA monthly PDFs", "rejected", KEY,
        "end-of-Congress PDF cadence; low value now"),
    Row(B, "regulatory", "eCFR bulk mirror", "`bulkdata/ECFR`", "rejected", NONE,
        "the catalog itself says \"not an official legal edition\"; the eCFR API is canonical"),
    Row(B, "regulatory", "Pre-1994 Federal Register PDFs", "FR collection", "rejected", KEY,
        "the only residual FR gap; revisit on historical-reach need"),
    # Table C: publisher XML, feeds and sites. Keyless; identity is what the sample shows.
    Row(C, "votes", "House per-vote XML", "`clerk.house.gov/evs/{year}/roll{N}.xml`", "candidate", NONE,
        "the `house-vote` API names this file as its source; bioguide-keyed", ("sample", "clerk-vote")),
    Row(C, "votes", "Senate per-vote XML", "`senate.gov/legislative/LIS/roll_call_votes/vote{c}{s}/vote_{c}_{s}_{n}.xml`",
        "candidate", NONE, "LIS-keyed, not bioguide; no Congress.gov route exists, so this is the only source",
        ("sample", "senate-vote")),
    Row(C, "members", "House MemberData.xml", "`clerk.house.gov/xml/lists/MemberData.xml`", "candidate", NONE,
        "members plus committee assignments with codes; only for fields the `member` API lacks", ("sample", "house-memberdata")),
    Row(C, "members", "House members.xml extras", "`member-info.house.gov/members.xml`", "candidate", NONE,
        "photos and social; only if the API lacks a needed field", ("sample", "house-members-xml")),
    Row(C, "members", "Senate committee XML", "`senate.gov/legislative/LIS_MEMBER/cvc_member_data.xml`", "candidate", NONE,
        "bioguide⇄LIS crosswalk, needed to join Senate votes to members", ("sample", "senate-cvc")),
    Row(C, "members", "Senate contact XML", "`senate.gov/general/contact_information/senators_cfm.xml`", "rejected", NONE,
        "cvc covers it", ("sample", "senate-contact")),
    Row(C, "members", "Bioguide bulk JSON", "`bioguide.congress.gov`", "rejected", NONE,
        "the `member` API is bioguide-keyed and tier-1; take only for biography text", ("cdtf", "67")),
    Row(C, "nominations", "Senate LIS nomination feeds (9)", "`senate.gov/legislative/LIS/nominations/Nom{Category}.xml`",
        "candidate", NONE, "alternative to the `nomination` API; take only for fields the API lacks",
        ("sample", "senate-nomination-feed")),
    Row(C, "proceedings", "House committee and floor repositories", "`docs.house.gov/committee`, `/floor` (weekly XML + RSS)",
        "candidate", NONE, "documents behind scheduled items; the `committee-meeting` API links here; the RSS measured 38.9 MB on 2026-09-18, so the weekly XML is the route", ("sample", "docs-house-floor-rss")),
    Row(C, "proceedings", "House Rules Committee", "`rules.house.gov`", "candidate", NONE,
        "amendment text and rules for floor bills; fills part of the amendment-text gap", ("cdtf", "85")),
    Row(C, "proceedings", "House floor summary", "`clerk.house.gov/floorsummary/floor-download.aspx` + RSS", "candidate", NONE,
        "timestamped floor chronology; unsampled", ("cdtf", "78")),
    Row(C, "proceedings", "Senate hearings calendar", "`senate.gov/general/committee_schedules/hearings.xml`", "candidate", NONE,
        "forward-looking only", ("sample", "senate-hearings")),
    Row(C, "proceedings", "Senate session calendar", "`senate.gov/legislative/{year}_schedule.xml`", "rejected", NONE,
        "trivial; the `congress` route states session dates", ("sample", "senate-calendar")),
    Row(C, "lobbying", "Senate LDA filings", "`lda.gov/api/v1/filings`", "have", "optional token", "`lda.py`",
        ("sample", "lda-filings"), ("src/spicy_docs/sources/lda.py",)),
    Row(C, "lobbying", "LDA contributions, registrants, clients, lobbyists", "`lda.gov/api/v1/{contributions,…}`", "candidate",
        "optional token", "URL builders on the existing family", ("sample", "lda-contributions")),
    Row(C, "lobbying", "House LDA filings", "`lobbyingdisclosure.house.gov`", "candidate", NONE, "the other half of LDA",
        ("cdtf", "81")),
    Row(C, "ethics", "House Clerk disclosures (financial, travel, mass comms, post-employment)", "clerk microsites", "rejected",
        NONE, "search-site PDFs; take per collection when a need names one", ("cdtf", "70")),
    Row(C, "ethics", "Senate financial disclosure and gifts", "`efdsearch.senate.gov`", "rejected", NONE,
        "agreement-gated search; not worth a driver", ("cdtf", "108")),
    Row(C, "spending", "House Statement of Disbursements", "`house.gov`, CSV since 2016", "candidate", NONE,
        "USAspending excludes Congress", ("cdtf", "86")),
    Row(C, "spending", "Report of the Secretary of the Senate", "`senate.gov`, PDF since 2011", "rejected", NONE,
        "PDF-only; revisit if XML or CSV appears", ("cdtf", "104")),
    Row(C, "spending", "PLUM report", "`opm.gov`, annual", "candidate", NONE,
        "\"thousands\" of filled and vacant senior positions per the catalog; no count verified", ("cdtf", "64")),
    Row(C, "gao", "GAO reports and testimony feed, files", "`gao.gov` RSS, `files.gao.gov`", "have", NONE,
        "`gao/rss.py`, `gao/files.py`", ("cdtf", "19"), ("src/spicy_docs/sources/gao/rss.py", "src/spicy_docs/sources/gao/files.py")),
    Row(C, "gao", "GAO product pages", "`gao.gov`", "have", "Zyte", "gated pages via `gao/native.py`", None,
        ("src/spicy_docs/sources/gao/native.py", "src/spicy_docs/sources/zyte.py")),
    Row(C, "gao", "GAO legal products and the restricted-reports list",
        "`gao.gov/legal/...`; `gao.gov/reports-testimonies/restricted`", "candidate", NONE,
        "appropriations-law decisions, bid protests and docket, other opinions", ("cdtf", "14")),
    Row(C, "cbo", "CBO cost-estimate feeds", "`cbo.gov/rss/{c}congress-cost-estimates.xml`", "have", NONE,
        "the one keyless route; every document route is a DataDome wall (`cbo.md`)", ("cdtf", "6"),
        ("src/spicy_docs/sources/cbo.py", "docs/sources/cbo.md")),
    Row(C, "jct", "Joint Committee on Taxation estimates and publications", "`jct.gov`", "candidate", NONE,
        "support agency absent from the catalog and the map; unsampled"),
    Row(C, "uscode", "US Code, Popular Names, Table III", "OLRC `uscode.house.gov`", "have", NONE, "`uscode/`", ("cdtf", "62"),
        ("src/spicy_docs/sources/uscode/__init__.py",)),
    Row(C, "uscode", "OLRC classification tables (per Congress)", "`uscode.house.gov/classification`", "candidate", NONE,
        "which Code sections each new public law touched; Table III is the historical act-section view"),
    Row(C, "crs", "CRS report PDFs", "`congress.gov/crs_external_products`", "have", NONE, "`crs_files.py`", None,
        ("src/spicy_docs/sources/congress/crs_files.py",)),
    Row(C, "reference", "CISA .gov domain registry", "`github.com/cisagov/dotgov-data`", "candidate", NONE,
        "agency-entity resolution CSV", ("cdtf", "11")),
    Row(C, "reference", "Appropriations status table", "`crsreports.congress.gov` HTML", "rejected", NONE, "low structure",
        ("cdtf", "53")),
    Row(C, "reference", "President's Budget Appendix, CBJs", "OMB, agencies", "rejected", NONE,
        "PDF-heavy; OMB non-compliant on format", ("cdtf", "63")),
    # Table D: civil society, BillTrax-side, and interpretation.
    Row(D, "crs", "EveryCRSReport bulk", "`everycrsreport.com` (AmericaLabs)", "candidate", NONE,
        "versioned and broader than congress.gov; verify maintenance cadence first", ("cdtf", "4")),
    Row(D, "members", "Community legislators YAML", "`unitedstates/congress-legislators`", "rejected", NONE,
        "port decision: PyYAML forbidden, community source, ~6 portable lines", None, (PORT_PLAN,)),
    Row(D, "press", "Press releases (member and committee RSS)", "varied", "port (unphased)", NONE,
        "plan section A assigns the RSS source to no phase; feed-URL unification is decision 5, blocking phase 2", None,
        (PORT_PLAN,)),
    Row(D, "reports", "Agency uploaded-report PDFs", "BillTrax uploads", "port 5", NONE, "`report-parser` ports; extraction channel",
        None, (PORT_PLAN,)),
    Row(D, "votes", "Bill⇄vote matching", "BillTrax", "rejected (here)", "n/a", "interpretation; stays BillTrax-side"),
    Row(D, "members", "Member matching", "BillTrax", "rejected (here)", "n/a", "interpretation"),
)  # fmt: skip


# --- keyless probe ------------------------------------------------------------


class ProbeError(ValueError):
    """A keyless probe refused: wrong media type, too large, or unreadable."""


class ProbeUnavailableError(ProbeError):
    def __init__(self, capture: CapturedBodyResponse) -> None:
        super().__init__(f"HTTP {capture.status_code}")
        self.capture = capture


class KeylessProbe(SourceAcquirer):
    """One bounded keyless GET per call; refusal bodies are retained like any keyless family."""

    def __init__(self, *, timeout_seconds: float, min_request_interval_seconds: float) -> None:
        super().__init__(
            max_requests=2,
            timeout_seconds=timeout_seconds,
            min_request_interval_seconds=min_request_interval_seconds,
            user_agent="spicy-docs-legislative-data-map/1.0",
            label="probe",
            error_type=ProbeError,
            context_key="probe",
            keyless=True,
        )

    def get(
        self, url: str, *, media_types: tuple[str, ...], max_bytes: int, accept: str | None = None
    ) -> CapturedBodyResponse:
        REQUESTS["keyless"] += 1
        _, capture = self.capture_validated(
            url,
            media_types=media_types,
            parse=lambda capture, _limit: capture,
            max_bytes=max_bytes,
            unavailable=ProbeUnavailableError,
            context={"operation": "probe", "url": url},
            request_headers={"Accept": accept} if accept else None,
        )
        return capture


def _capture_facts(capture: CapturedBodyResponse) -> dict[str, Any]:
    return {
        "resolvedUrl": capture.resolved_url,
        "statusCode": capture.status_code,
        "contentType": capture.content_type,
        "byteSize": capture.byte_size,
        "sha256": capture.sha256,
        "observedAt": capture.observed_at,
    }


def _error(error: Exception, api_key: str = "") -> dict[str, Any]:
    facts: dict[str, Any] = {"error": type(error).__name__, "message": scrub_credential(str(error), api_key)[:300]}
    capture = getattr(error, "capture", None)
    if isinstance(capture, CapturedBodyResponse):
        facts["statusCode"] = capture.status_code
        facts["contentType"] = capture.content_type
    return facts


# --- Congress.gov ---------------------------------------------------------------


def _congress_url(path: str) -> str:
    return f"{CONGRESS_API}/{path}?{urlencode({'format': 'json', 'limit': 1})}"


def _count(reader: PagedJsonReader, url: str, records_key: str) -> int:
    REQUESTS[reader.family.name] += 1
    page = reader.page(url, records_key=records_key)
    return page.declared_count if page.declared_count is not None else len(page.records)


def measure_congress(reader: CongressListingReader, *, max_descent: int, api_key: str) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for route in CONGRESS_ROUTES:
        facts: dict[str, Any] = {"recordsKey": route.records_key}
        try:
            facts["total"] = _count(reader, _congress_url(route.route), route.records_key)
        except (PagedJsonSourceError, httpx.HTTPError) as error:
            facts["totalError"] = _error(error, api_key)
        if route.descent is None:
            out[route.route] = facts
            continue
        counts: dict[int, int] = {}
        errors: dict[int, dict[str, Any]] = {}
        earliest: int | None = None
        empty_after = leading_empty = 0
        stop = "cap"
        for step in range(max_descent):
            key = route.start - step
            if key < 1:
                stop = "floor"
                break
            try:
                count = _count(reader, _congress_url(route.descent.format(c=key)), route.records_key)
            except (PagedJsonSourceError, httpx.HTTPError) as error:
                # A publisher error is not an observation of emptiness; a few are tolerated, then the walk stops.
                errors[key] = _error(error, api_key)
                if len(errors) >= ERROR_TOLERANCE:
                    stop = "error"
                    break
                continue
            counts[key] = count
            if count > 0:
                earliest, empty_after = key, 0
            elif earliest is None:
                leading_empty += 1
                if leading_empty >= LEADING_EMPTY_TOLERANCE:
                    stop = "never-populated"
                    break
            else:
                empty_after += 1
                if empty_after >= 2:
                    stop = "two-empty"
                    break
        facts.update(
            {"descentPath": route.descent, "earliest": earliest, "descentStop": stop, "byKey": counts, "errors": errors}
        )
        out[route.route] = facts
        print(f"congress {route.route}: total={facts.get('total')} earliest={earliest} stop={stop}", file=sys.stderr)
    return out


# --- GovInfo -------------------------------------------------------------------


def _published_count(reader: GovInfoDiscoveryReader, code: str, year: int) -> int:
    return _count(reader, published_url(f"{year}-01-01", collections=[code], page_size=1), "packages")


def measure_govinfo(reader: GovInfoDiscoveryReader, probe: KeylessProbe, *, api_key: str) -> dict[str, Any]:
    out: dict[str, Any] = {"collections": {}, "coverage": {}, "bulkdata": {}}
    REQUESTS[reader.family.name] += 1
    page = reader.page(f"{GOVINFO_API}/collections", records_key="collections")
    for record in page.records:
        code = str(record.get("collectionCode", ""))
        out["collections"][code] = {
            "name": record.get("collectionName"),
            "packageCount": record.get("packageCount"),
            "granuleCount": record.get("granuleCount"),
        }
    for code in GOVINFO_COVERAGE:
        if code not in out["collections"]:
            out["coverage"][code] = {"error": "not in the collections inventory"}
            continue
        try:
            total = _published_count(reader, code, FIRST_YEAR)
            low, high = FIRST_YEAR, CURRENT_YEAR
            if total == 0:
                out["coverage"][code] = {"total": 0, "earliestYear": None}
                continue
            while low < high:
                mid = (low + high + 1) // 2
                if _published_count(reader, code, mid) == total:
                    low = mid
                else:
                    high = mid - 1
            out["coverage"][code] = {"total": total, "earliestYear": low}
        except (PagedJsonSourceError, httpx.HTTPError) as error:
            out["coverage"][code] = _error(error, api_key)
        print(f"govinfo {code}: {out['coverage'][code]}", file=sys.stderr)
    for code in sorted(out["collections"]):
        try:
            capture = probe.get(
                f"{GOVINFO_BULK}/{code}", media_types=JSON_TYPES, max_bytes=4 * 1024 * 1024, accept="application/json"
            )
            files = json.loads(capture.body).get("files", [])
        except ProbeError:
            continue
        folders = [str(f.get("name")) for f in files if f.get("folder")]
        numeric = sorted(int(n) for n in folders if n.isdigit())
        out["bulkdata"][code] = {
            "folders": len(folders),
            "numericRange": [numeric[0], numeric[-1]] if numeric else None,
            "topLevelFiles": sum(1 for f in files if not f.get("folder")),
            "topLevelBytes": sum(int(f.get("size") or 0) for f in files if not f.get("folder")),
            **_capture_facts(capture),
        }
    return out


# --- catalog and samples -------------------------------------------------------


def measure_catalog(probe: KeylessProbe) -> dict[str, Any]:
    capture = probe.get(CDTF_CATALOG, media_types=JSON_TYPES, max_bytes=8 * 1024 * 1024)
    datasets = json.loads(capture.body)["dataset"]

    def landing(entry: Mapping) -> str:
        page = entry.get("landingPage")
        return str(page.get("accessURL", "")) if isinstance(page, dict) else str(page or "")

    roots = deep = missing = 0
    for entry in datasets:
        for dist in entry.get("distribution", []):
            url = dist.get("accessURL")
            if not url:
                missing += 1
            elif urlsplit(url).path.strip("/"):
                deep += 1
            else:
                roots += 1
    landings = Counter(landing(e) for e in datasets if landing(e))
    entries = {
        e["identifier"].removeprefix("CDTF-DATASET-"): {
            "title": e.get("title"),
            "accrualPeriodicity": e.get("accrualPeriodicity"),
            "landingPage": landing(e),
        }
        for e in datasets
    }
    return {
        **_capture_facts(capture),
        "entries": len(datasets),
        "withAccrualPeriodicity": sum(1 for e in datasets if e.get("accrualPeriodicity")),
        "withFormatOrTemporal": sum(
            1
            for e in datasets
            if e.get("temporal") or any(d.get("format") or d.get("mediaType") for d in e.get("distribution", []))
        ),
        "distributionAccessUrl": {"homepageRoot": roots, "deep": deep, "missing": missing},
        "duplicateLandingPages": {url: n for url, n in landings.items() if n > 1},
        "byId": entries,
    }


def _xml_shape(body: bytes, key: str) -> dict[str, Any]:
    root = parse_xml(
        body, max_bytes=len(body), error_type=ProbeError, label=key, allow_external_doctype=True, max_depth=64
    )

    def local(tag: str) -> str:
        return tag.rsplit("}", 1)[-1]

    children = Counter(local(child.tag) for child in root)
    namespace = root.tag[1:].split("}", 1)[0] if root.tag.startswith("{") else None
    return {
        "root": local(root.tag),
        "namespace": namespace,
        "rootAttributes": sorted(root.attrib),
        "children": dict(children.most_common(12)),
        "childCount": sum(children.values()),
    }


def measure_samples(probe: KeylessProbe) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for key, (url, media_types) in SAMPLES.items():
        try:
            capture = probe.get(url, media_types=media_types, max_bytes=SAMPLE_MAX_BYTES)
            facts = {"url": url, **_capture_facts(capture)}
            if media_types is JSON_TYPES:
                value = json.loads(capture.body)
                facts["shape"] = (
                    {"keys": sorted(value)[:12], "count": value.get("count")} if isinstance(value, dict) else {}
                )
            else:
                facts["shape"] = _xml_shape(capture.body, key)
        except (ProbeError, ValueError) as error:
            facts = {"url": url, **_error(error)}
        out[key] = facts
        print(f"sample {key}: {facts.get('statusCode', facts.get('error'))}", file=sys.stderr)
    return out


# --- rendering -----------------------------------------------------------------


def _ordinal(n: int) -> str:
    suffix = "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def _cell(text: object) -> str:
    return str(text if text is not None else "").replace("|", "\\|").replace("\n", " ")


def _congress_cells(facts: Mapping[str, Any]) -> tuple[str, str]:
    if "totalError" in facts and "earliest" not in facts:
        return "error", facts["totalError"].get("message", "")[:60]
    total = facts.get("total")
    count = f"{total:,}" if isinstance(total, int) else ""
    earliest = facts.get("earliest")
    if earliest is None:
        coverage = "" if "descentPath" not in facts else f"none found ({facts.get('descentStop')})"
    else:
        unit = "vol." if "record" in facts.get("descentPath", "") and "daily" in facts.get("descentPath", "") else ""
        label = (
            f"{unit} {earliest}"
            if unit
            else (str(earliest) if "bound" in facts.get("descentPath", "") else f"{_ordinal(earliest)} Congress")
        )
        coverage = f"≥ {label}" if facts.get("descentStop") in ("cap", "error") else f"{label}+"
        if facts.get("descentStop") in ("cap", "error"):
            coverage += f" ({facts['descentStop']})"
    return coverage, count


def _govinfo_cells(measures: Mapping[str, Any], code: str) -> tuple[str, str]:
    inventory = measures.get("collections", {}).get(code, {})
    coverage = measures.get("coverage", {}).get(code, {})
    bulk = measures.get("bulkdata", {}).get(code)
    year = coverage.get("earliestYear")
    cov = [f"API {year}+" if year else ("API error" if coverage.get("error") else "")]
    if bulk:
        rng = bulk.get("numericRange")
        cov.append(f"bulk {rng[0]}–{rng[1]}" if rng else "bulk, flat")
    parts = []
    if isinstance(inventory.get("packageCount"), int):
        parts.append(f"{inventory['packageCount']:,} pkgs")
    if bulk and bulk.get("topLevelFiles"):
        parts.append(f"bulk {bulk['topLevelFiles']:,} files, {bulk['topLevelBytes'] / 1e6:,.0f} MB")
    return "; ".join(c for c in cov if c), "; ".join(parts)


def _sample_cells(facts: Mapping[str, Any]) -> tuple[str, str]:
    if "error" in facts:
        reason = facts.get("message", facts["error"]).split(";")[0][:70]
        return "", f"sample refused: HTTP {facts['statusCode']}" if facts.get(
            "statusCode"
        ) else f"sample refused: {reason}"
    shape = facts.get("shape", {})
    root = shape.get("root")
    if root:
        detail = f"root `{root}`, {shape.get('childCount', 0)} children"
    elif isinstance(shape.get("count"), int):
        detail = f"declares {shape['count']:,} records"
    else:
        detail = f"keys {', '.join(shape.get('keys', [])[:4])}"
    return "", f"sample {facts.get('byteSize', 0):,} B, {detail}"


def _cells(row: Row, measures: Mapping[str, Any]) -> tuple[str, str]:
    if row.measure is None:
        return "", ""
    kind, key = row.measure
    if kind == "congress":
        return _congress_cells(measures.get("congress", {}).get(key, {}))
    if kind == "govinfo":
        return _govinfo_cells(measures.get("govinfo", {}), key)
    if kind == "sample":
        return _sample_cells(measures.get("samples", {}).get(key, {}))
    if kind == "cdtf":
        entry = measures.get("catalog", {}).get("byId", {}).get(key, {})
        return str(entry.get("accrualPeriodicity", "")), f"CDTF #{key}"
    raise ValueError(f"unknown measure kind {kind!r}")


TABLES = {
    A: "Table A: Congress.gov API. One credential family, one pagination contract, one reader; a route is a URL builder and a records key.",
    B: "Table B: GovInfo API and bulkdata. Discovery and MODS already reach any collection; what differs per collection is the body fetch.",
    C: "Table C: publisher XML, feeds and sites. Keyless; the sample column shows what the payload states about itself.",
    D: "Table D: civil society, BillTrax-side and interpretation.",
}


def render_tables(measures: Mapping[str, Any]) -> str:
    lines = [MARK_START, ""]
    generated = measures.get("generatedAt", "")
    lines.append(
        f"Measured {generated[:10]} by `tools/analysis/legislative_data_map.py` at spicy-docs `{measures.get('revision', '')}`; "
        f"{measures.get('requests', {}).get('total', '?')} requests. Coverage is the earliest populated Congress, volume or "
        f"year the publisher answered for, a lower bound; `(cap)` means the walk ended at its request cap and `(error)` "
        f"that it stopped on repeated publisher errors, both detailed in the JSON."
    )
    lines.append("")
    for table, caption in TABLES.items():
        lines += [
            f"### {caption}",
            "",
            "| Subject | Data | Route | Status | Credential | Coverage | Count / sample | Note |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for row in ROWS:
            if row.table != table:
                continue
            coverage, count = _cells(row, measures)
            lines.append(
                "| "
                + " | ".join(
                    _cell(v)
                    for v in (
                        row.subject,
                        row.data,
                        row.route,
                        f"`{row.status}`",
                        row.credential,
                        coverage,
                        count,
                        row.note,
                    )
                )
                + " |"
            )
        lines.append("")
    catalog = measures.get("catalog", {})
    dist = catalog.get("distributionAccessUrl", {})
    duplicates = ", ".join(f"`{u}` ×{n}" for u, n in catalog.get("duplicateLandingPages", {}).items()) or "none"
    lines.append("### Catalog measurements")
    lines.append("")
    lines.append(
        f"- CDTF entries: {catalog.get('entries')}; with `accrualPeriodicity`: {catalog.get('withAccrualPeriodicity')}; "
        f"with any format or temporal field: {catalog.get('withFormatOrTemporal')}."
    )
    lines.append(
        f"- `distribution.accessURL`: {dist.get('homepageRoot')} bare homepage roots, {dist.get('deep')} deep links, "
        f"{dist.get('missing')} missing. The real URL is `landingPage.accessURL`, nested in an object."
    )
    lines.append(f"- Duplicate landing pages: {duplicates}.")
    lines.append("")
    lines.append(MARK_END)
    return "\n".join(lines)


def rewrite_map(path: Path, tables: str) -> None:
    text = path.read_text()
    start, end = text.find(MARK_START), text.find(MARK_END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit(f"{path} lacks the generated-table markers")
    path.write_text(text[:start] + tables + text[end + len(MARK_END) :])


# --- main ----------------------------------------------------------------------


def check_evidence(root: Path) -> None:
    missing = [(row.data, p) for row in ROWS for p in row.evidence if not (root / p).exists()]
    claims = [row.data for row in ROWS if row.status.startswith(("have", "port")) and not row.evidence]
    if missing or claims:
        for data, p in missing:
            print(f"evidence missing for {data!r}: {p}", file=sys.stderr)
        for data in claims:
            print(f"no evidence named for {data!r}", file=sys.stderr)
        raise SystemExit(2)


def _revision(root: Path) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], cwd=root, capture_output=True, text=True, check=False
    )
    return result.stdout.strip() or "unknown"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--output", type=Path, required=True, help="measurements JSON; read instead of measured with --offline"
    )
    parser.add_argument("--map", type=Path, required=True, help="the markdown map whose generated tables are rewritten")
    parser.add_argument("--env-file", type=Path, help="file holding the api.data.gov key")
    parser.add_argument("--env-var", default="API_GOV")
    parser.add_argument("--offline", action="store_true")
    parser.add_argument("--max-descent", type=int, default=60, help="requests per route when walking back by Congress")
    parser.add_argument("--min-interval-seconds", type=float, default=0.3)
    parser.add_argument("--timeout", type=float, default=60.0)
    args = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[2]
    check_evidence(root)
    if args.offline:
        measures = json.loads(args.output.read_text())
    else:
        if args.env_file is None:
            parser.error("--env-file is required unless --offline")
        api_key = read_api_key(args.env_file, args.env_var)
        budget = PagedJsonBudget(
            max_requests=3,
            max_page_bytes=4 * 1024 * 1024,
            timeout_seconds=args.timeout,
            min_request_interval_seconds=args.min_interval_seconds,
        )
        measures: dict[str, Any] = {"generatedAt": datetime.now(UTC).isoformat(), "revision": _revision(root)}
        try:
            with (
                CongressListingReader(budget=budget, api_key=api_key) as congress,
                GovInfoDiscoveryReader(budget=budget, api_key=api_key) as govinfo,
                KeylessProbe(
                    timeout_seconds=args.timeout, min_request_interval_seconds=args.min_interval_seconds
                ) as probe,
            ):

                def checkpoint() -> None:
                    args.output.write_text(json.dumps(measures, indent=2, sort_keys=True) + "\n")

                measures["congress"] = measure_congress(congress, max_descent=args.max_descent, api_key=api_key)
                checkpoint()
                measures["govinfo"] = measure_govinfo(govinfo, probe, api_key=api_key)
                checkpoint()
                measures["catalog"] = measure_catalog(probe)
                checkpoint()
                measures["samples"] = measure_samples(probe)
                measures["requests"] = dict(REQUESTS)
        except CredentialRefusedError as error:
            print(f"credential refused; stopping: {scrub_credential(str(error), api_key)}", file=sys.stderr)
            return 1
        measures["requests"]["total"] = sum(measures["requests"].values())
        measures["rows"] = [asdict(row) for row in ROWS]
        args.output.write_text(json.dumps(measures, indent=2, sort_keys=True) + "\n")
    rewrite_map(args.map, render_tables(measures))
    print(json.dumps({"output": str(args.output), "map": str(args.map), "requests": measures.get("requests")}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
