"""Measure committed captures, without invoking a converter or making requests.

Every metric maps to a field in the review's critical metadata inventory.
Repeated fields count every applicable instance; a field counts as complete
only when all instances are present. A zero denominator is not applicable.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from pathlib import Path
from typing import Any

from spicy_docs.schemas.document_capture.provenance import (
    GOVINFO_FAMILIES,
    PDF_FAMILIES,
    check_archive_member,
    check_provenance,
    coordinate_fields_present,
    decision_required,
    full_timestamp,
)

ROOT = Path(__file__).resolve().parents[2]
BASELINE = "053c1fbb3a01dff1b9ecb0308f1a26f9d6518448"


def git(*args: str) -> bytes:
    return subprocess.run(["git", *args], cwd=ROOT, check=True, capture_output=True).stdout


def inventory(capture: dict[str, Any], observations: dict[str, Any]) -> dict[str, dict[str, int]]:
    """Presence in the stored capture, not inferred values generated by its producer."""
    out = {}

    def field(name: str, values: list[Any]) -> None:
        out[name] = {"present": sum(bool(v) for v in values), "total": len(values)}

    def scalar(name: str, value: Any, applicable: bool = True) -> None:
        field(name, [value] if applicable else [])

    family = capture["profile"]["name"]
    ext = capture["profile"]["ext"]
    artifact = capture["artifact"]
    rendition = capture["rendition"]
    source = ext.get("archiveMember", {}).get("archive") or ext.get("derivedFrom") or artifact
    govinfo = family in GOVINFO_FAMILIES
    pdf = family in PDF_FAMILIES
    identity = ext.get("govinfoIdentity", {})
    records = ext.get("sourceRecords", [])
    mods = [r for r in records if r.get("role") == "mods"]
    fields = [f for r in mods for f in r.get("sourceFields", [])]
    scalar("1.govinfoPackageId", identity.get("packageId") or ext.get("packageId"), govinfo)
    scalar("1.govinfoGranuleId", "granuleId" in identity or bool(ext.get("granuleId")), govinfo)
    scalar("1.pairedGovinfoIdentity", identity.get("packageId") and "granuleId" in identity, govinfo)
    scalar("2.modsIdentity", any(r.get("packageId") and "granuleId" in r for r in mods), govinfo)
    scalar("2.modsEvidence", any(r.get("path") and r.get("sha256") and r.get("identityPaths") for r in mods), govinfo)
    url = source.get("url") or source.get("locator", {}).get("url")
    observed = observations.get(url, {})
    scalar("3.publisherUrl", url and all(source.get(k) == observed.get(k) for k in ("sha256", "byteSize", "mediaType")))
    for key in ("sha256", "byteSize", "mediaType"):
        scalar(f"4.artifact.{key}", artifact.get(key))
    scalar("4.fullRetrievalTime", full_timestamp(source.get("retrievedAt")))
    scalar(
        "4.acquisitionRecord",
        any(r.get("role") == "acquisition" and r.get("receipt", {}).get("sha256") for r in records),
    )
    scalar("5.renditionKind", rendition.get("kind"))
    scalar("5.textStreamDigest", rendition["textStream"].get("sha256"))
    scalar("5.normalization", rendition["textStream"].get("normalization"))
    scalar("5.extractorIntermediate", rendition.get("intermediate"), pdf)
    scalar("5.renditionReason", ext.get("renditionReason"))
    spans = capture["evidence"]
    defaults = rendition.get("spanDefaults", {})
    field(
        "6.spanCharacterProvenance",
        [
            s.get("exact")
            and "start" in s
            and "end" in s
            and coordinate_fields_present({**defaults, **s.get("source", {})})
            for s in spans
        ],
    )
    # Empty source elements and empty observed cells have no character evidence
    # to invent. Every node carrying text, or children with text, must resolve.
    by_id = {n["id"]: bool(n.get("evidence")) for n in capture["nodes"]}
    for n in reversed(capture["nodes"]):
        if n["parent"] and by_id[n["id"]]:
            by_id[n["parent"]] = True
    field(
        "6.nodeCharacterEvidence",
        [by_id[n["id"]] for n in capture["nodes"] if n.get("text", "").strip() or by_id[n["id"]]],
    )
    sources = [n.get("source", {}) for n in capture["nodes"]] + [{**defaults, **s.get("source", {})} for s in spans]
    regions = [s for s in sources if s.get("coordinateSystem") == "page-region"]
    field("6.pageNumber", [s.get("page") for s in regions])
    field("6.pageBox", [coordinate_fields_present(s) for s in regions])
    pages = {s["page"] for s in regions if s.get("page")}
    sizes = {p["page"]: p for p in ext.get("pageSizes", [])}
    sizes.update(
        {n.get("source", {}).get("page"): n.get("pageSize", {}) for n in capture["nodes"] if n["kind"] == "page"}
    )
    field(
        "6.pageDimensions",
        [
            sizes.get(p, {}).get("width") and sizes.get(p, {}).get("height") and sizes[p].get("unit") == "point"
            for p in sorted(pages)
        ],
    )
    for key in ("version", "implementation", "dependencies"):
        scalar(f"7.converter.{key}", capture["converter"].get(key))
    scalar("7.profilePin", capture["profile"].get("schema", {}).get("sha256"))
    field(
        "7.nodeDecision",
        [
            n.get("decision", {}).get("method") and n.get("decision", {}).get("rule")
            for n in capture["nodes"]
            if decision_required(n)
        ],
    )
    scalar("7.dedicatedRuleVersion", ext.get("ruleVersions"))
    scalar(
        "8.billLawIdentity",
        ext.get("congress")
        and (ext.get("docNumber") or (ext.get("billType") and ext.get("billNumber") and ext.get("version"))),
        family in {"bill-xml", "uslm-law"},
    )
    scalar("8.normalizedBillId", ext.get("bill_id"), family == "bill-xml")
    scalar("8.citationTargetList", ext.get("citationTargets"))
    scalar("9.uscTargets", ext.get("uscTargets"), family in {"uslm-law", "bill-xml", "senate-expenditures-pdf"})
    scalar("9.frCitation", ext.get("citation"), family == "federal-register-xml")
    scalar("9.docketIds", "docketIds" in ext, family == "federal-register-xml")
    scalar("9.rins", "regulationIdNumbers" in ext, family == "federal-register-xml")
    scalar(
        "9.committeeCodes",
        any(f["name"] == "congCommittee" and f["attributes"].get("authorityId") for f in fields),
        family == "committee-report-html",
    )
    scalar(
        "9.publicationApprovalDate",
        ext.get("publicationDate")
        or ext.get("approvedDate")
        or any(f["name"] == "dateIssued" and f["value"] for f in fields),
        family in {"uslm-law", "federal-register-xml", "committee-report-html", "senate-expenditures-pdf"},
    )
    cells = [n for n in capture["nodes"] if n["kind"] == "cell"]
    scalar("10.tableStructure", any(n["kind"] == "table" for n in capture["nodes"]), bool(cells))
    field("10.cellRowColumn", ["row" in n.get("cell", {}) and "column" in n.get("cell", {}) for n in cells])
    for key in ("rowSpan", "columnSpan", "header"):
        field(f"10.cell.{key}", [key in n.get("cell", {}) for n in cells])
    field(
        "10.cellPageBox",
        [
            n.get("source", {}).get("coordinateSystem") == "page-region" and coordinate_fields_present(n["source"])
            for n in cells
        ]
        if pdf
        else [],
    )
    return out


def measure(before: str, after: str) -> dict[str, Any]:
    before = git("rev-parse", before).decode().strip()
    after = git("rev-parse", after).decode().strip()
    paths = git("ls-tree", "-r", "--name-only", after).decode().splitlines()
    paths = sorted(p for p in paths if p.endswith(".capture.json"))
    previous = {
        p for p in git("ls-tree", "-r", "--name-only", before).decode().splitlines() if p.endswith(".capture.json")
    }
    if set(paths) != previous:
        raise ValueError("capture population changed; select and explain the comparison population explicitly")
    observation_path = "tests/fixtures/document_capture_provenance/observations.json"
    observation_bytes = git("show", f"{after}:{observation_path}")
    observations = {r["observation"]["url"]: r["observation"] for r in json.loads(observation_bytes)}
    rows = []
    inputs = {}
    for path in paths:
        row = {"path": path}
        for label, revision in (("before", before), ("after", after)):
            raw = git("show", f"{revision}:{path}")
            capture = json.loads(raw)
            if label == "after":
                ext = capture["profile"]["ext"]
                records = [capture["artifact"], *ext.get("sourceRecords", [])]
                records.extend(
                    [
                        capture["rendition"].get("intermediate", {}),
                        ext.get("derivedFrom", {}),
                        ext.get("archiveMember", {}).get("archive", {}),
                    ]
                )
                for record in records:
                    source_path = record.get("path") or record.get("locator", {}).get("path")
                    if source_path:
                        inputs[source_path] = {
                            "path": source_path,
                            "sha256": record["sha256"],
                            "bytes": record["byteSize"],
                        }
            metrics = inventory(capture, observations)
            row["family"] = capture["profile"]["name"]
            row[label] = {
                "sha256": hashlib.sha256(raw).hexdigest(),
                "bytes": len(raw),
                "fields": metrics,
                "completeFields": sum(v["total"] > 0 and v["present"] == v["total"] for v in metrics.values()),
                "applicableFields": sum(v["total"] > 0 for v in metrics.values()),
                "findings": check_provenance(capture),
            }
        rows.append(row)
    for path in (
        "tests/fixtures/reconstruction/cfr/README.md",
        "tests/fixtures/document_capture_pdf_tables/source.json",
        "docs/research/document-capture-schema-2026-09-19/inputs/fr-2026-19200.json",
        "src/spicy_docs/schemas/document_capture/1.0/PINS.json",
    ):
        data = git("show", f"{after}:{path}")
        inputs[path] = {"path": path, "sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)}
    original_zip_receipt = json.loads(
        git("show", f"{after}:tests/fixtures/document_capture_provenance/public-law.json")
    )["receipt"]
    return {
        "beforeCommit": before,
        "afterCommit": after,
        "requests": 0,
        "captureCount": len(rows),
        "observationInput": {"path": observation_path, "sha256": hashlib.sha256(observation_bytes).hexdigest()},
        "retainedReceipts": [*[r["receipt"] for r in json.loads(observation_bytes)], original_zip_receipt],
        "retainedInputs": list(inputs.values()),
        "families": rows,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--before", default=BASELINE)
    parser.add_argument("--after", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--verify-retained",
        action="store_true",
        help="Hash retained inputs and receipts and verify the real ZIP member; still zero requests",
    )
    args = parser.parse_args()
    result = measure(args.before, args.after)
    if args.verify_retained:
        for pin in [*result["retainedInputs"], *result["retainedReceipts"]]:
            data = (ROOT / pin["path"]).read_bytes()
            if hashlib.sha256(data).hexdigest() != pin["sha256"]:
                raise ValueError(f"retained input digest mismatch: {pin['path']}")
            if "bytes" in pin and len(data) != pin["bytes"]:
                raise ValueError(f"retained input size mismatch: {pin['path']}")
        law_path = next(r["path"] for r in result["families"] if r["family"] == "uslm-law")
        capture = json.loads(git("show", f"{result['afterCommit']}:{law_path}"))
        archive = capture["profile"]["ext"]["archiveMember"]["archive"]
        if findings := check_archive_member(capture, Path(archive["path"]).read_bytes()):
            raise ValueError(findings)
        result["retainedVerification"] = {"inputsAndReceipts": "all digests match", "archiveAndMember": "both match"}
    args.output.write_text(json.dumps(result, indent=2) + "\n")
    for row in result["families"]:
        a, b = row["before"], row["after"]
        print(
            f"{row['family']}: {a['completeFields']}/{a['applicableFields']} -> {b['completeFields']}/{b['applicableFields']}; findings {len(a['findings'])} -> {len(b['findings'])}"
        )


if __name__ == "__main__":
    main()
